// ============================================================
// えいごクイズ 問題データ（英検対策）
// ------------------------------------------------------------
// ※ このファイルは ツール/『2_Excel→questions.py』が
//    【問題作成用】.xlsx から自動生成します。手で直しても、
//    次に反映すると上書きされます。編集は Excel 側で行ってください。
//
//   生成日時: 2026-07-06 12:34
//   問題数  : 460 問
// ============================================================

const QUESTIONS = [

  // ===== Lv1  学習1 アルファベット =====
  {lv:1, stage:"alpha", q:"大文字の A の 小文字は どれ？", c:["a", "e", "c", "o"], a:0, kw:"A / a", em:"🔤", yomi:"エー", rel:[], exp:"A の小文字は a。"},
  {lv:1, stage:"alpha", q:"大文字の B の 小文字は どれ？", c:["b", "d", "p", "q"], a:0, kw:"B / b", em:"🔤", yomi:"ビー", rel:[], exp:"B の小文字は b。"},
  {lv:1, stage:"alpha", q:"大文字の C の 小文字は どれ？", c:["c", "o", "e", "a"], a:0, kw:"C / c", em:"🔤", yomi:"スィー", rel:[], exp:"C の小文字は c。"},
  {lv:1, stage:"alpha", q:"大文字の D の 小文字は どれ？", c:["d", "b", "p", "g"], a:0, kw:"D / d", em:"🔤", yomi:"ディー", rel:[], exp:"D の小文字は d。"},
  {lv:1, stage:"alpha", q:"大文字の E の 小文字は どれ？", c:["e", "c", "a", "o"], a:0, kw:"E / e", em:"🔤", yomi:"イー", rel:[], exp:"E の小文字は e。"},
  {lv:1, stage:"alpha", q:"大文字の G の 小文字は どれ？", c:["g", "q", "j", "y"], a:0, kw:"G / g", em:"🔤", yomi:"ジー", rel:[], exp:"G の小文字は g。"},
  {lv:1, stage:"alpha", q:"大文字の H の 小文字は どれ？", c:["h", "n", "b", "k"], a:0, kw:"H / h", em:"🔤", yomi:"エイチ", rel:[], exp:"H の小文字は h。"},
  {lv:1, stage:"alpha", q:"大文字の N の 小文字は どれ？", c:["n", "m", "h", "r"], a:0, kw:"N / n", em:"🔤", yomi:"エヌ", rel:[], exp:"N の小文字は n。"},
  {lv:1, stage:"alpha", q:"大文字の Q の 小文字は どれ？", c:["q", "g", "p", "o"], a:0, kw:"Q / q", em:"🔤", yomi:"キュー", rel:[], exp:"Q の小文字は q。"},
  {lv:1, stage:"alpha", q:"大文字の R の 小文字は どれ？", c:["r", "n", "p", "k"], a:0, kw:"R / r", em:"🔤", yomi:"アール", rel:[], exp:"R の小文字は r。"},
  {lv:1, stage:"alpha", q:"小文字の b の 大文字は どれ？", c:["B", "D", "P", "R"], a:0, kw:"b / B", em:"🔡", yomi:"ビー", rel:[], exp:"b の大文字は B。"},
  {lv:1, stage:"alpha", q:"小文字の d の 大文字は どれ？", c:["D", "B", "O", "Q"], a:0, kw:"d / D", em:"🔡", yomi:"ディー", rel:[], exp:"d の大文字は D。"},
  {lv:1, stage:"alpha", q:"小文字の g の 大文字は どれ？", c:["G", "Q", "C", "J"], a:0, kw:"g / G", em:"🔡", yomi:"ジー", rel:[], exp:"g の大文字は G。"},
  {lv:1, stage:"alpha", q:"小文字の m の 大文字は どれ？", c:["M", "N", "W", "H"], a:0, kw:"m / M", em:"🔡", yomi:"エム", rel:[], exp:"m の大文字は M。"},
  {lv:1, stage:"alpha", q:"小文字の p の 大文字は どれ？", c:["P", "B", "R", "D"], a:0, kw:"p / P", em:"🔡", yomi:"ピー", rel:[], exp:"p の大文字は P。"},
  {lv:1, stage:"alpha", q:"小文字の r の 大文字は どれ？", c:["R", "P", "B", "K"], a:0, kw:"r / R", em:"🔡", yomi:"アール", rel:[], exp:"r の大文字は R。"},
  {lv:1, stage:"alpha", q:"小文字の y の 大文字は どれ？", c:["Y", "V", "X", "T"], a:0, kw:"y / Y", em:"🔡", yomi:"ワイ", rel:[], exp:"y の大文字は Y。"},
  {lv:1, stage:"alpha", q:"ABC順で A の つぎは どれ？", c:["B", "C", "D", "E"], a:0, kw:"ABC順", em:"🔢", rel:[], exp:"A→B。"},
  {lv:1, stage:"alpha", q:"ABC順で E の つぎは どれ？", c:["F", "D", "G", "H"], a:0, kw:"ABC順", em:"🔢", rel:[], exp:"E→F。"},
  {lv:1, stage:"alpha", q:"ABC順で H の つぎは どれ？", c:["I", "G", "J", "K"], a:0, kw:"ABC順", em:"🔢", rel:[], exp:"H→I。"},
  {lv:1, stage:"alpha", q:"ABC順で M の つぎは どれ？", c:["N", "L", "O", "K"], a:0, kw:"ABC順", em:"🔢", rel:[], exp:"M→N。"},
  {lv:1, stage:"alpha", q:"ABC順で T の つぎは どれ？", c:["U", "S", "V", "R"], a:0, kw:"ABC順", em:"🔢", rel:[], exp:"T→U。"},
  {lv:1, stage:"alpha", q:"アルファベットで いちばん さいごの 文字は どれ？", c:["Z", "W", "X", "Y"], a:0, kw:"Z", em:"🔚", yomi:"ゼット", rel:[], exp:"最後は Z。"},
  {lv:1, stage:"alpha", q:"アルファベットは ぜんぶで 何文字？", c:["26", "24", "25", "28"], a:0, kw:"26文字", em:"🔢", rel:[], exp:"A〜Z で26文字。"},
  {lv:1, stage:"alpha", q:"母音（ぼいん）だけ ならんでいるのは どれ？", c:["A, E, I, O, U", "B, C, D, F, G", "K, L, M, N, P", "W, X, Y, Z, V"], a:0, kw:"母音", em:"🔡", rel:[], exp:"母音は a・e・i・o・u の5つ。"},
  {lv:1, stage:"phonics", q:"cat の さいしょの 音は どれ？", c:["/k/ ク", "/s/ ス", "/t/ トゥ", "/a/ ア"], a:0, kw:"c", em:"🐱", rel:[], exp:"c は /k/ の音。"},
  {lv:1, stage:"phonics", q:"dog の さいしょの 音は どれ？", c:["/d/ ド", "/t/ トゥ", "/g/ グ", "/o/ オ"], a:0, kw:"d", em:"🐶", rel:[], exp:"d は /d/ の音。"},
  {lv:1, stage:"phonics", q:"sun の さいしょの 音は どれ？", c:["/s/ ス", "/n/ ン", "/u/ ア", "/m/ ム"], a:0, kw:"s", em:"☀️", rel:[], exp:"s は /s/ の音。"},
  {lv:1, stage:"phonics", q:"map の さいしょの 音は どれ？", c:["/m/ ム", "/p/ プ", "/a/ ア", "/b/ ブ"], a:0, kw:"m", em:"🗺️", rel:[], exp:"m は /m/ の音。"},
  {lv:1, stage:"phonics", q:"fish の さいしょの 音は どれ？", c:["/f/ フ", "/sh/ シュ", "/i/ イ", "/h/ ハ"], a:0, kw:"f", em:"🐟", rel:[], exp:"f は /f/ の音。"},

  // ===== Lv2  学習2 かず・いろ =====
  {lv:2, stage:"num", q:"1 は 英語で どれ？", c:["one", "two", "three", "four"], a:0, kw:"one", em:"1️⃣", yomi:"ワン", rel:[], exp:"1 は one。"},
  {lv:2, stage:"num", q:"2 は 英語で どれ？", c:["two", "ten", "twelve", "three"], a:0, kw:"two", em:"2️⃣", yomi:"トゥー", rel:[], exp:"2 は two。"},
  {lv:2, stage:"num", q:"3 は 英語で どれ？", c:["three", "free", "tree", "third"], a:0, kw:"three", em:"3️⃣", yomi:"スリー", rel:[], exp:"3 は three。"},
  {lv:2, stage:"num", q:"4 は 英語で どれ？", c:["four", "five", "for", "fork"], a:0, kw:"four", em:"4️⃣", yomi:"フォー", rel:[], exp:"4 は four。"},
  {lv:2, stage:"num", q:"5 は 英語で どれ？", c:["five", "fine", "four", "nine"], a:0, kw:"five", em:"5️⃣", yomi:"ファイブ", rel:[], exp:"5 は five。"},
  {lv:2, stage:"num", q:"6 は 英語で どれ？", c:["six", "seven", "sick", "ten"], a:0, kw:"six", em:"6️⃣", yomi:"シックス", rel:[], exp:"6 は six。"},
  {lv:2, stage:"num", q:"7 は 英語で どれ？", c:["seven", "eleven", "eight", "six"], a:0, kw:"seven", em:"7️⃣", yomi:"セブン", rel:[], exp:"7 は seven。"},
  {lv:2, stage:"num", q:"8 は 英語で どれ？", c:["eight", "eighty", "eat", "nine"], a:0, kw:"eight", em:"8️⃣", yomi:"エイト", rel:[], exp:"8 は eight。"},
  {lv:2, stage:"num", q:"9 は 英語で どれ？", c:["nine", "five", "ninety", "line"], a:0, kw:"nine", em:"9️⃣", yomi:"ナイン", rel:[], exp:"9 は nine。"},
  {lv:2, stage:"num", q:"10 は 英語で どれ？", c:["ten", "two", "teen", "tent"], a:0, kw:"ten", em:"🔟", yomi:"テン", rel:[], exp:"10 は ten。"},
  {lv:2, stage:"num", q:"11 は 英語で どれ？", c:["eleven", "seven", "twelve", "twenty"], a:0, kw:"eleven", em:"🔢", yomi:"イレブン", rel:[], exp:"11 は eleven。"},
  {lv:2, stage:"num", q:"12 は 英語で どれ？", c:["twelve", "twenty", "two", "ten"], a:0, kw:"twelve", em:"🔢", yomi:"トゥエルブ", rel:[], exp:"12 は twelve。"},
  {lv:2, stage:"num", q:"0 は 英語で どれ？", c:["zero", "one", "ten", "two"], a:0, kw:"zero", em:"0️⃣", yomi:"ゼロ", rel:[], exp:"0 は zero。"},
  {lv:2, stage:"num", q:"20 は 英語で どれ？", c:["twenty", "twelve", "two", "twelfth"], a:0, kw:"twenty", em:"🔢", yomi:"トゥエンティ", rel:[], exp:"20 は twenty。"},
  {lv:2, stage:"color", q:"red は 何色？", c:["あか", "あお", "きいろ", "みどり"], a:0, kw:"red", em:"🔴", yomi:"レッド", rel:[], exp:"red は 赤。"},
  {lv:2, stage:"color", q:"blue は 何色？", c:["あお", "みどり", "むらさき", "くろ"], a:0, kw:"blue", em:"🔵", yomi:"ブルー", rel:[], exp:"blue は 青。"},
  {lv:2, stage:"color", q:"yellow は 何色？", c:["きいろ", "しろ", "ちゃいろ", "ピンク"], a:0, kw:"yellow", em:"🟡", yomi:"イエロー", rel:[], exp:"yellow は 黄色。"},
  {lv:2, stage:"color", q:"green は 何色？", c:["みどり", "あお", "あか", "オレンジ"], a:0, kw:"green", em:"🟢", yomi:"グリーン", rel:[], exp:"green は 緑。"},
  {lv:2, stage:"color", q:"「くろ」は 英語で どれ？", c:["black", "brown", "blue", "white"], a:0, kw:"black", em:"⚫", yomi:"ブラック", rel:[], exp:"黒は black。"},
  {lv:2, stage:"color", q:"「しろ」は 英語で どれ？", c:["white", "yellow", "pink", "gray"], a:0, kw:"white", em:"⚪", yomi:"ホワイト", rel:[], exp:"白は white。"},
  {lv:2, stage:"color", q:"pink は 何色？", c:["ピンク", "むらさき", "あか", "ちゃいろ"], a:0, kw:"pink", em:"🩷", yomi:"ピンク", rel:[], exp:"pink は 桃色。"},
  {lv:2, stage:"color", q:"「むらさき」は 英語で どれ？", c:["purple", "orange", "green", "blue"], a:0, kw:"purple", em:"🟣", yomi:"パープル", rel:[], exp:"紫は purple。"},
  {lv:2, stage:"color", q:"orange は 何色？", c:["オレンジ", "みどり", "きいろ", "あか"], a:0, kw:"orange", em:"🟠", yomi:"オレンジ", rel:[], exp:"orange は だいだい色。"},
  {lv:2, stage:"color", q:"「ちゃいろ」は 英語で どれ？", c:["brown", "black", "blue", "pink"], a:0, kw:"brown", em:"🟤", yomi:"ブラウン", rel:[], exp:"茶色は brown。"},
  {lv:2, stage:"color", q:"gray は 何色？", c:["はいいろ", "くろ", "しろ", "ちゃいろ"], a:0, kw:"gray", em:"🩶", yomi:"グレー", rel:[], exp:"gray は 灰色。"},
  {lv:2, stage:"color", q:"circle は 何の 形？", c:["まる", "さんかく", "しかく", "ほし"], a:0, kw:"circle", em:"⭕", yomi:"サークル", rel:[], exp:"circle は 円。"},
  {lv:2, stage:"color", q:"「しかく」は 英語で どれ？", c:["square", "circle", "star", "heart"], a:0, kw:"square", em:"🟦", yomi:"スクエア", rel:[], exp:"四角は square。"},
  {lv:2, stage:"color", q:"triangle は 何の 形？", c:["さんかく", "まる", "しかく", "ほし"], a:0, kw:"triangle", em:"🔺", yomi:"トライアングル", rel:[], exp:"triangle は 三角。"},
  {lv:2, stage:"color", q:"「ほし」の 形は 英語で どれ？", c:["star", "moon", "heart", "circle"], a:0, kw:"star", em:"⭐", yomi:"スター", rel:[], exp:"星は star。"},
  {lv:2, stage:"color", q:"heart は 何の 形？", c:["ハート", "ほし", "まる", "つき"], a:0, kw:"heart", em:"❤️", yomi:"ハート", rel:[], exp:"heart は ハート。"},

  // ===== Lv3  学習3 みぢかな単語 =====
  {lv:3, stage:"word", q:"dog の 意味は？", c:["いぬ", "ねこ", "とり", "うま"], a:0, kw:"dog", em:"🐶", yomi:"ドッグ", rel:[], exp:"dog は 犬。"},
  {lv:3, stage:"word", q:"cat の 意味は？", c:["ねこ", "いぬ", "うさぎ", "ねずみ"], a:0, kw:"cat", em:"🐱", yomi:"キャット", rel:[], exp:"cat は 猫。"},
  {lv:3, stage:"word", q:"bird の 意味は？", c:["とり", "さかな", "むし", "うし"], a:0, kw:"bird", em:"🐦", yomi:"バード", rel:[], exp:"bird は 鳥。"},
  {lv:3, stage:"word", q:"fish の 意味は？", c:["さかな", "とり", "いぬ", "かえる"], a:0, kw:"fish", em:"🐟", yomi:"フィッシュ", rel:[], exp:"fish は 魚。"},
  {lv:3, stage:"word", q:"「うさぎ」は 英語で どれ？", c:["rabbit", "horse", "mouse", "monkey"], a:0, kw:"rabbit", em:"🐰", yomi:"ラビット", rel:[], exp:"うさぎは rabbit。"},
  {lv:3, stage:"word", q:"horse の 意味は？", c:["うま", "うし", "ぶた", "いぬ"], a:0, kw:"horse", em:"🐴", yomi:"ホース", rel:[], exp:"horse は 馬。"},
  {lv:3, stage:"word", q:"monkey の 意味は？", c:["さる", "くま", "ぞう", "ライオン"], a:0, kw:"monkey", em:"🐵", yomi:"モンキー", rel:[], exp:"monkey は 猿。"},
  {lv:3, stage:"word", q:"「ぞう」は 英語で どれ？", c:["elephant", "lion", "bear", "tiger"], a:0, kw:"elephant", em:"🐘", yomi:"エレファント", rel:[], exp:"象は elephant。"},
  {lv:3, stage:"word", q:"apple の 意味は？", c:["りんご", "みかん", "ぶどう", "バナナ"], a:0, kw:"apple", em:"🍎", yomi:"アップル", rel:[], exp:"apple は りんご。"},
  {lv:3, stage:"word", q:"banana の 意味は？", c:["バナナ", "りんご", "いちご", "もも"], a:0, kw:"banana", em:"🍌", yomi:"バナナ", rel:[], exp:"banana は バナナ。"},
  {lv:3, stage:"word", q:"「みず」は 英語で どれ？", c:["water", "milk", "juice", "tea"], a:0, kw:"water", em:"💧", yomi:"ウォーター", rel:[], exp:"水は water。"},
  {lv:3, stage:"word", q:"milk の 意味は？", c:["ぎゅうにゅう", "みず", "ジュース", "おちゃ"], a:0, kw:"milk", em:"🥛", yomi:"ミルク", rel:[], exp:"milk は 牛乳。"},
  {lv:3, stage:"word", q:"bread の 意味は？", c:["パン", "ごはん", "たまご", "にく"], a:0, kw:"bread", em:"🍞", yomi:"ブレッド", rel:[], exp:"bread は パン。"},
  {lv:3, stage:"word", q:"「たまご」は 英語で どれ？", c:["egg", "rice", "meat", "bread"], a:0, kw:"egg", em:"🥚", yomi:"エッグ", rel:[], exp:"卵は egg。"},
  {lv:3, stage:"word", q:"rice の 意味は？", c:["ごはん・こめ", "パン", "にく", "スープ"], a:0, kw:"rice", em:"🍚", yomi:"ライス", rel:[], exp:"rice は ごはん・米。"},
  {lv:3, stage:"word", q:"「にく」は 英語で どれ？", c:["meat", "fish", "egg", "soup"], a:0, kw:"meat", em:"🍖", yomi:"ミート", rel:[], exp:"肉は meat。"},
  {lv:3, stage:"word", q:"head の 意味は？", c:["あたま", "て", "あし", "め"], a:0, kw:"head", em:"🧑", yomi:"ヘッド", rel:[], exp:"head は 頭。"},
  {lv:3, stage:"word", q:"hand の 意味は？", c:["て", "あし", "みみ", "はな"], a:0, kw:"hand", em:"✋", yomi:"ハンド", rel:[], exp:"hand は 手。"},
  {lv:3, stage:"word", q:"eye の 意味は？", c:["め", "みみ", "はな", "くち"], a:0, kw:"eye", em:"👁️", yomi:"アイ", rel:[], exp:"eye は 目。"},
  {lv:3, stage:"word", q:"「みみ」は 英語で どれ？", c:["ear", "eye", "nose", "mouth"], a:0, kw:"ear", em:"👂", yomi:"イヤー", rel:[], exp:"耳は ear。"},
  {lv:3, stage:"word", q:"nose の 意味は？", c:["はな", "くち", "め", "みみ"], a:0, kw:"nose", em:"👃", yomi:"ノーズ", rel:[], exp:"nose は 鼻。"},
  {lv:3, stage:"word", q:"mouth の 意味は？", c:["くち", "はな", "て", "あし"], a:0, kw:"mouth", em:"👄", yomi:"マウス", rel:[], exp:"mouth は 口。"},
  {lv:3, stage:"word", q:"「あし（足）」は 英語で どれ？", c:["foot", "hand", "head", "arm"], a:0, kw:"foot", em:"🦶", yomi:"フット", rel:[], exp:"足は foot。"},
  {lv:3, stage:"word", q:"hair の 意味は？", c:["かみのけ", "て", "め", "はな"], a:0, kw:"hair", em:"💇", yomi:"ヘア", rel:[], exp:"hair は 髪の毛。"},
  {lv:3, stage:"word", q:"father の 意味は？", c:["おとうさん", "おかあさん", "おにいさん", "おじいさん"], a:0, kw:"father", em:"👨", yomi:"ファーザー", rel:[], exp:"father は お父さん。"},
  {lv:3, stage:"word", q:"mother の 意味は？", c:["おかあさん", "おとうさん", "おねえさん", "おばあさん"], a:0, kw:"mother", em:"👩", yomi:"マザー", rel:[], exp:"mother は お母さん。"},
  {lv:3, stage:"word", q:"「おにいさん・おとうと」は 英語で どれ？", c:["brother", "sister", "father", "uncle"], a:0, kw:"brother", em:"👦", yomi:"ブラザー", rel:[], exp:"兄・弟は brother。"},
  {lv:3, stage:"word", q:"sister の 意味は？", c:["おねえさん・いもうと", "おにいさん", "おかあさん", "おばさん"], a:0, kw:"sister", em:"👧", yomi:"シスター", rel:[], exp:"sister は 姉・妹。"},
  {lv:3, stage:"word", q:"「おじいさん」は 英語で どれ？", c:["grandfather", "grandmother", "father", "uncle"], a:0, kw:"grandfather", em:"👴", yomi:"グランドファーザー", rel:[], exp:"祖父は grandfather。"},
  {lv:3, stage:"word", q:"grandmother の 意味は？", c:["おばあさん", "おじいさん", "おかあさん", "おばさん"], a:0, kw:"grandmother", em:"👵", yomi:"グランドマザー", rel:[], exp:"grandmother は 祖母。"},

  // ===== Lv4  学習4 あいさつ =====
  {lv:4, stage:"greet", q:"「おはよう（午前）」は 英語で？", c:["Good morning", "Good night", "Goodbye", "Good afternoon"], a:0, kw:"Good morning", em:"🌅", yomi:"グッドモーニング", rel:[], exp:"朝のあいさつ。"},
  {lv:4, stage:"greet", q:"「こんにちは（昼）」は 英語で？", c:["Good afternoon", "Good morning", "Good evening", "Good night"], a:0, kw:"Good afternoon", em:"🌞", yomi:"グッドアフタヌーン", rel:[], exp:"昼のあいさつ。"},
  {lv:4, stage:"greet", q:"「こんばんは」は 英語で？", c:["Good evening", "Good morning", "Good night", "Hello"], a:0, kw:"Good evening", em:"🌆", yomi:"グッドイブニング", rel:[], exp:"夜のあいさつ。"},
  {lv:4, stage:"greet", q:"「おやすみ」は 英語で？", c:["Good night", "Good morning", "Goodbye", "Hello"], a:0, kw:"Good night", em:"🌙", yomi:"グッドナイト", rel:[], exp:"寝る前のあいさつ。"},
  {lv:4, stage:"greet", q:"「やあ／どうも」は 英語で？", c:["Hello", "Goodbye", "Sorry", "Please"], a:0, kw:"Hello", em:"👋", yomi:"ハロー", rel:[], exp:"いつでも使えるあいさつ。"},
  {lv:4, stage:"greet", q:"「ありがとう」は 英語で？", c:["Thank you", "Sorry", "Please", "Hello"], a:0, kw:"Thank you", em:"🙏", yomi:"サンキュー", rel:[], exp:"感謝は Thank you。"},
  {lv:4, stage:"greet", q:"Thank you. への 返事は？", c:["You're welcome.", "Good night.", "Me too.", "Here you are."], a:0, kw:"返事", em:"😊", rel:[], exp:"「どういたしまして」。"},
  {lv:4, stage:"greet", q:"「ごめんなさい」は 英語で？", c:["I'm sorry.", "Thank you.", "Please.", "Excuse me."], a:0, kw:"I'm sorry", em:"😢", yomi:"アイム ソーリー", rel:[], exp:"謝るときは I'm sorry.。"},
  {lv:4, stage:"greet", q:"人に声をかける「すみません」は？", c:["Excuse me.", "Good night.", "Well done.", "See you."], a:0, kw:"Excuse me", em:"🙋", yomi:"イクスキューズ ミー", rel:[], exp:"呼びかけ・通してもらう時。"},
  {lv:4, stage:"greet", q:"「はじめまして」は 英語で？", c:["Nice to meet you.", "See you.", "I'm fine.", "Good night."], a:0, kw:"Nice to meet you", em:"🤝", rel:[], exp:"はじめて会った人へ。"},
  {lv:4, stage:"greet", q:"Nice to meet you. への 返しは？", c:["Nice to meet you, too.", "No, thank you.", "It's mine.", "Good night."], a:0, kw:"返し", em:"🤝", rel:[], exp:"〜, too. で返す。"},
  {lv:4, stage:"greet", q:"「さようなら」は 英語で？", c:["Goodbye", "Hello", "Welcome", "Sorry"], a:0, kw:"Goodbye", em:"👋", yomi:"グッバイ", rel:[], exp:"別れのあいさつ。"},
  {lv:4, stage:"greet", q:"「またね」は 英語で？", c:["See you.", "Hello.", "Thank you.", "Sorry."], a:0, kw:"See you", em:"🙋", yomi:"シー ユー", rel:[], exp:"別れぎわの一言。"},
  {lv:4, stage:"greet", q:"How are you? への 答えは？", c:["I'm fine, thank you.", "Good morning.", "You're welcome.", "It's Monday."], a:0, kw:"体調", em:"😀", rel:[], exp:"「元気です」。"},
  {lv:4, stage:"greet", q:"「また明日」は 英語で？", c:["See you tomorrow.", "Good morning.", "Thank you.", "Here you are."], a:0, kw:"See you tomorrow", em:"📅", rel:[], exp:"別れのあいさつ。"},
  {lv:4, stage:"greet", q:"物を手渡す「はい、どうぞ」は？", c:["Here you are.", "Goodbye.", "I'm sorry.", "Stand up."], a:0, kw:"Here you are", em:"🤲", rel:[], exp:"物をわたすときの一言。"},
  {lv:4, stage:"greet", q:"「お誕生日おめでとう」は？", c:["Happy birthday!", "Good night.", "Thank you.", "See you."], a:0, kw:"Happy birthday", em:"🎂", yomi:"ハッピー バースデイ", rel:[], exp:"誕生日のお祝い。"},
  {lv:4, stage:"greet", q:"「どうぞ・お願いします」は？", c:["Please.", "Sorry.", "Hello.", "Goodbye."], a:0, kw:"Please", em:"🙏", yomi:"プリーズ", rel:[], exp:"ていねいなお願い。"},
  {lv:4, stage:"greet", q:"先生の「立ってください」は？", c:["Stand up.", "Sit down.", "Open your book.", "Be quiet."], a:0, kw:"Stand up", em:"🧍", rel:[], exp:"「立ちなさい」。"},
  {lv:4, stage:"greet", q:"先生の「すわってください」は？", c:["Sit down.", "Stand up.", "Look at me.", "Close your book."], a:0, kw:"Sit down", em:"🪑", rel:[], exp:"「すわりなさい」。"},
  {lv:4, stage:"greet", q:"先生の「本を開いて」は？", c:["Open your book.", "Close your book.", "Stand up.", "Raise your hand."], a:0, kw:"Open your book", em:"📖", rel:[], exp:"「本を開いて」。"},
  {lv:4, stage:"greet", q:"先生の「本を閉じて」は？", c:["Close your book.", "Open your book.", "Sit down.", "Listen to me."], a:0, kw:"Close your book", em:"📕", rel:[], exp:"「本を閉じて」。"},
  {lv:4, stage:"greet", q:"先生の「わたしを見て」は？", c:["Look at me.", "Listen to me.", "Stand up.", "Be quiet."], a:0, kw:"Look at me", em:"👀", rel:[], exp:"「わたしを見て」。"},
  {lv:4, stage:"greet", q:"先生の「しずかにして」は？", c:["Be quiet.", "Stand up.", "Open your book.", "Good job."], a:0, kw:"Be quiet", em:"🤫", rel:[], exp:"「しずかに」。"},
  {lv:4, stage:"greet", q:"先生の「よく聞いて」は？", c:["Listen.", "Look.", "Write.", "Read."], a:0, kw:"Listen", em:"👂", yomi:"リスン", rel:[], exp:"「聞きなさい」。"},
  {lv:4, stage:"greet", q:"先生の「手をあげて」は？", c:["Raise your hand.", "Stand up.", "Sit down.", "Open your book."], a:0, kw:"Raise your hand", em:"🙋", rel:[], exp:"「手をあげて」。"},
  {lv:4, stage:"greet", q:"先生の「くり返して言って」は？", c:["Repeat after me.", "Look at me.", "Be quiet.", "Sit down."], a:0, kw:"Repeat after me", em:"🔁", rel:[], exp:"「後についてくり返して」。"},
  {lv:4, stage:"greet", q:"「よくできました」は 英語で？", c:["Good job!", "Goodbye.", "I'm sorry.", "See you."], a:0, kw:"Good job", em:"👍", yomi:"グッジョブ", rel:[], exp:"ほめる言葉。"},
  {lv:4, stage:"greet", q:"先生の「はじめましょう」は？", c:["Let's begin.", "Good night.", "Thank you.", "Stand up."], a:0, kw:"Let's begin", em:"▶️", rel:[], exp:"授業のはじまり。"},
  {lv:4, stage:"greet", q:"Any questions? の 意味は？", c:["質問はありますか？", "立ちなさい", "すわりなさい", "静かに"], a:0, kw:"Any questions?", em:"❓", rel:[], exp:"「質問ある？」。"},

  // ===== Lv5  学習5 動き・様子 =====
  {lv:5, stage:"verb", q:"run の 意味は？", c:["はしる", "あるく", "たべる", "ねる"], a:0, kw:"run", em:"🏃", yomi:"ラン", rel:["walk"], exp:"run は 走る。"},
  {lv:5, stage:"verb", q:"walk の 意味は？", c:["あるく", "はしる", "とぶ", "およぐ"], a:0, kw:"walk", em:"🚶", yomi:"ウォーク", rel:["run"], exp:"walk は 歩く。"},
  {lv:5, stage:"verb", q:"eat の 意味は？", c:["たべる", "のむ", "みる", "きく"], a:0, kw:"eat", em:"🍽️", yomi:"イート", rel:["drink"], exp:"eat は 食べる。"},
  {lv:5, stage:"verb", q:"drink の 意味は？", c:["のむ", "たべる", "つくる", "かう"], a:0, kw:"drink", em:"🥤", yomi:"ドリンク", rel:["eat"], exp:"drink は 飲む。"},
  {lv:5, stage:"verb", q:"「ねる」は 英語で どれ？", c:["sleep", "wake", "sit", "stand"], a:0, kw:"sleep", em:"😴", yomi:"スリープ", rel:[], exp:"寝るは sleep。"},
  {lv:5, stage:"verb", q:"look の 意味は？", c:["みる", "きく", "はなす", "よむ"], a:0, kw:"look", em:"👀", yomi:"ルック", rel:["see"], exp:"look は 見る。"},
  {lv:5, stage:"verb", q:"read の 意味は？", c:["よむ", "かく", "はなす", "うたう"], a:0, kw:"read", em:"📚", yomi:"リード", rel:["write"], exp:"read は 読む。"},
  {lv:5, stage:"verb", q:"write の 意味は？", c:["かく", "よむ", "けす", "きる"], a:0, kw:"write", em:"✍️", yomi:"ライト", rel:["read"], exp:"write は 書く。"},
  {lv:5, stage:"verb", q:"「あそぶ・（球技を）する」は 英語で？", c:["play", "stop", "help", "cook"], a:0, kw:"play", em:"⚽", yomi:"プレイ", rel:[], exp:"play は 遊ぶ。"},
  {lv:5, stage:"verb", q:"sing の 意味は？", c:["うたう", "おどる", "はしる", "とぶ"], a:0, kw:"sing", em:"🎤", yomi:"シング", rel:[], exp:"sing は 歌う。"},
  {lv:5, stage:"verb", q:"swim の 意味は？", c:["およぐ", "とぶ", "はしる", "あるく"], a:0, kw:"swim", em:"🏊", yomi:"スイム", rel:[], exp:"swim は 泳ぐ。"},
  {lv:5, stage:"verb", q:"「とぶ・ジャンプする」は 英語で？", c:["jump", "run", "walk", "sit"], a:0, kw:"jump", em:"🤸", yomi:"ジャンプ", rel:[], exp:"跳ぶは jump。"},
  {lv:5, stage:"verb", q:"go の 意味は？", c:["いく", "くる", "する", "みる"], a:0, kw:"go", em:"➡️", yomi:"ゴー", rel:["come"], exp:"go は 行く。"},
  {lv:5, stage:"verb", q:"come の 意味は？", c:["くる", "いく", "たべる", "ねる"], a:0, kw:"come", em:"⬅️", yomi:"カム", rel:["go"], exp:"come は 来る。"},
  {lv:5, stage:"verb", q:"make の 意味は？", c:["つくる", "こわす", "かう", "うる"], a:0, kw:"make", em:"🔨", yomi:"メイク", rel:[], exp:"make は 作る。"},
  {lv:5, stage:"verb", q:"study の 意味は？", c:["勉強する", "あそぶ", "ねる", "はしる"], a:0, kw:"study", em:"📖", yomi:"スタディ", rel:[], exp:"study は 勉強する。"},
  {lv:5, stage:"adj", q:"big の 意味は？（反対は small）", c:["おおきい", "ちいさい", "はやい", "あたらしい"], a:0, kw:"big", em:"🐘", yomi:"ビッグ", rel:["small"], exp:"big は 大きい。"},
  {lv:5, stage:"adj", q:"「ちいさい」は 英語で どれ？", c:["small", "big", "tall", "long"], a:0, kw:"small", em:"🐜", yomi:"スモール", rel:["big"], exp:"小さいは small。"},
  {lv:5, stage:"adj", q:"new の 意味は？", c:["あたらしい", "ふるい", "あつい", "さむい"], a:0, kw:"new", em:"✨", yomi:"ニュー", rel:["old"], exp:"new は 新しい。"},
  {lv:5, stage:"adj", q:"old の 意味は？", c:["ふるい", "あたらしい", "わかい", "おおきい"], a:0, kw:"old", em:"📜", yomi:"オールド", rel:["new"], exp:"old は 古い。"},
  {lv:5, stage:"adj", q:"hot の 意味は？", c:["あつい", "さむい", "あまい", "からい"], a:0, kw:"hot", em:"🔥", yomi:"ホット", rel:["cold"], exp:"hot は 熱い・暑い。"},
  {lv:5, stage:"adj", q:"「さむい・つめたい」は 英語で どれ？", c:["cold", "hot", "warm", "cool"], a:0, kw:"cold", em:"❄️", yomi:"コールド", rel:["hot"], exp:"寒い・冷たいは cold。"},
  {lv:5, stage:"adj", q:"fast の 意味は？", c:["はやい", "おそい", "つよい", "よわい"], a:0, kw:"fast", em:"⚡", yomi:"ファスト", rel:["slow"], exp:"fast は 速い。"},
  {lv:5, stage:"adj", q:"slow の 意味は？", c:["おそい", "はやい", "ながい", "みじかい"], a:0, kw:"slow", em:"🐢", yomi:"スロー", rel:["fast"], exp:"slow は 遅い。"},
  {lv:5, stage:"adj", q:"long の 意味は？", c:["ながい", "みじかい", "たかい", "ひくい"], a:0, kw:"long", em:"📏", yomi:"ロング", rel:["short"], exp:"long は 長い。"},
  {lv:5, stage:"adj", q:"「みじかい」は 英語で どれ？", c:["short", "long", "tall", "small"], a:0, kw:"short", em:"📐", yomi:"ショート", rel:["long"], exp:"短いは short。"},
  {lv:5, stage:"adj", q:"happy の 意味は？", c:["うれしい", "かなしい", "おこった", "ねむい"], a:0, kw:"happy", em:"😄", yomi:"ハッピー", rel:["sad"], exp:"happy は うれしい。"},
  {lv:5, stage:"adj", q:"sad の 意味は？", c:["かなしい", "うれしい", "たのしい", "こわい"], a:0, kw:"sad", em:"😢", yomi:"サッド", rel:["happy"], exp:"sad は 悲しい。"},
  {lv:5, stage:"adj", q:"good の 意味は？", c:["よい", "わるい", "おおきい", "はやい"], a:0, kw:"good", em:"👍", yomi:"グッド", rel:["bad"], exp:"good は 良い。"},
  {lv:5, stage:"adj", q:"bad の 意味は？", c:["わるい", "よい", "あたらしい", "ちいさい"], a:0, kw:"bad", em:"👎", yomi:"バッド", rel:["good"], exp:"bad は 悪い。"},

  // ===== Lv6  学習6 はじめての文 =====
  {lv:6, stage:"sentence", q:"「わたしは ケンです」= I ___ Ken.", c:["am", "is", "are", "be"], a:0, kw:"I am", em:"🙂", rel:[], exp:"I のあとは am。"},
  {lv:6, stage:"sentence", q:"「あなたは 生徒です」= You ___ a student.", c:["are", "am", "is", "do"], a:0, kw:"You are", em:"🧑‍🎓", rel:[], exp:"You のあとは are。"},
  {lv:6, stage:"sentence", q:"「彼は 父です」= He ___ my father.", c:["is", "am", "are", "do"], a:0, kw:"He is", em:"👨", rel:[], exp:"He のあとは is。"},
  {lv:6, stage:"sentence", q:"「彼女は 先生です」= She ___ a teacher.", c:["is", "are", "am", "be"], a:0, kw:"She is", em:"👩‍🏫", rel:[], exp:"She のあとは is。"},
  {lv:6, stage:"sentence", q:"「それは ねこです」= It ___ a cat.", c:["is", "are", "am", "do"], a:0, kw:"It is", em:"🐱", rel:[], exp:"It のあとは is。"},
  {lv:6, stage:"sentence", q:"「わたしたちは 友だちです」= We ___ friends.", c:["are", "am", "is", "be"], a:0, kw:"We are", em:"👫", rel:[], exp:"We のあとは are。"},
  {lv:6, stage:"sentence", q:"「彼らは 犬です」= They ___ dogs.", c:["are", "is", "am", "do"], a:0, kw:"They are", em:"🐶", rel:[], exp:"They のあとは are。"},
  {lv:6, stage:"sentence", q:"「これは ペンです」= This ___ a pen.", c:["is", "am", "are", "do"], a:0, kw:"This is", em:"🖊️", rel:[], exp:"This のあとは is。"},
  {lv:6, stage:"sentence", q:"「あれは 鳥です」= That ___ a bird.", c:["is", "are", "am", "do"], a:0, kw:"That is", em:"🐦", rel:[], exp:"That のあとは is。"},
  {lv:6, stage:"sentence", q:"「わたしは 犬が すき」= I ___ dogs.", c:["like", "likes", "am", "liking"], a:0, kw:"I like", em:"🐶", rel:[], exp:"主語 I なので like。"},
  {lv:6, stage:"sentence", q:"「わたしは かばんを もっている」= I ___ a bag.", c:["have", "has", "am", "do"], a:0, kw:"I have", em:"🎒", rel:[], exp:"I のときは have。"},
  {lv:6, stage:"sentence", q:"「わたしは 泳げる」= I ___ swim.", c:["can", "am", "do", "is"], a:0, kw:"I can", em:"🏊", rel:[], exp:"「〜できる」は can+動詞。"},
  {lv:6, stage:"sentence", q:"「彼女は 泳げる」= She ___ swim.", c:["can", "cans", "is", "does"], a:0, kw:"can", em:"🏊", rel:[], exp:"can は主語が変わっても形は同じ。"},
  {lv:6, stage:"sentence", q:"「これは 何ですか」= ___ is this?", c:["What", "Who", "Where", "When"], a:0, kw:"What", em:"❓", rel:[], exp:"「何」は What。"},
  {lv:6, stage:"sentence", q:"「これは 何色ですか」= ___ color is this?", c:["What", "Who", "When", "Why"], a:0, kw:"What color", em:"🎨", rel:[], exp:"What+名詞で「何の〜」。"},
  {lv:6, stage:"sentence", q:"「わたしは サッカーが すき」の 正しい語順は？", c:["I like soccer.", "I soccer like.", "Like I soccer.", "Soccer I like."], a:0, kw:"語順", em:"⚽", rel:[], exp:"〈主語+動詞+目的語〉。"},
  {lv:6, stage:"sentence", q:"「わたしは 医者では ない」= I am ___ a doctor.", c:["not", "no", "don't", "isn't"], a:0, kw:"否定", em:"🚫", rel:[], exp:"be動詞の否定は am not。"},
  {lv:6, stage:"sentence", q:"「あなたは 学生ですか」= ___ you a student?", c:["Are", "Is", "Am", "Do"], a:0, kw:"疑問", em:"❔", rel:[], exp:"You の be動詞疑問文は Are you〜?。"},
  {lv:6, stage:"sentence", q:"「わたしは 納豆が すきではない」= I ___ like natto.", c:["don't", "not", "isn't", "doesn't"], a:0, kw:"一般動詞の否定", em:"🚫", rel:[], exp:"一般動詞の否定は don't+動詞。"},
  {lv:6, stage:"sentence", q:"「あなたは 犬が すき？」= ___ you like dogs?", c:["Do", "Are", "Does", "Is"], a:0, kw:"一般動詞の疑問", em:"❔", rel:[], exp:"一般動詞の疑問は Do you〜?。"},
  {lv:6, stage:"sentence", q:"「彼は テニスを する」= He ___ tennis.", c:["plays", "play", "playing", "are"], a:0, kw:"三単現", em:"🎾", rel:[], exp:"He など3人称単数は plays。"},
  {lv:6, stage:"sentence", q:"「本が 2さつ」= two ___", c:["books", "book", "bookes", "books's"], a:0, kw:"複数形", em:"📚", rel:[], exp:"2つ以上は s をつけて books。"},
  {lv:6, stage:"sentence", q:"「りんご 1個」= ___", c:["an apple", "a apple", "apple an", "the a apple"], a:0, kw:"a / an", em:"🍎", rel:[], exp:"母音の音の前は an。"},
  {lv:6, stage:"sentence", q:"「ドアを 開けて」= ___ the door.", c:["Open", "Opens", "Opening", "To open"], a:0, kw:"命令文", em:"🚪", rel:[], exp:"命令文は動詞で始める。"},
  {lv:6, stage:"sentence", q:"「わたしは 走っている」= I am ___.", c:["running", "run", "runs", "to run"], a:0, kw:"現在進行形", em:"🏃", rel:[], exp:"am+動詞ing で「〜している」。"},
  {lv:6, stage:"sentence", q:"「わたしの 本」= ___ book", c:["my", "I", "me", "mine"], a:0, kw:"my", em:"📗", rel:[], exp:"「わたしの」は my。"},
  {lv:6, stage:"sentence", q:"「机の上に ねこが いる」= There ___ a cat on the desk.", c:["is", "are", "am", "be"], a:0, kw:"There is", em:"🐱", rel:[], exp:"単数なので There is。"},
  {lv:6, stage:"sentence", q:"「サッカーを しよう」= ___ play soccer.", c:["Let's", "Let", "We's", "Do"], a:0, kw:"Let's", em:"⚽", rel:[], exp:"「〜しよう」は Let's+動詞。"},
  {lv:6, stage:"sentence", q:"「わたしは 学校へ 行く」= I ___ to school.", c:["go", "goes", "going", "am go"], a:0, kw:"go to", em:"🏫", rel:[], exp:"主語 I なので go。行き先は to。"},
  {lv:6, stage:"sentence", q:"「彼女は ケンが すき」= She ___ Ken.", c:["likes", "like", "is", "liking"], a:0, kw:"三単現", em:"💕", rel:[], exp:"She なので likes。"},

  // ===== Lv7  学習7 曜日・天気 =====
  {lv:7, stage:"calendar", q:"Sunday は 何曜日？", c:["日曜日", "土曜日", "月曜日", "金曜日"], a:0, kw:"Sunday", em:"📅", yomi:"サンデイ", rel:[], exp:"日曜日。"},
  {lv:7, stage:"calendar", q:"Monday は 何曜日？", c:["月曜日", "日曜日", "火曜日", "木曜日"], a:0, kw:"Monday", em:"📅", yomi:"マンデイ", rel:[], exp:"月曜日。"},
  {lv:7, stage:"calendar", q:"Tuesday は 何曜日？", c:["火曜日", "木曜日", "水曜日", "月曜日"], a:0, kw:"Tuesday", em:"📅", yomi:"テューズデイ", rel:[], exp:"火曜日。"},
  {lv:7, stage:"calendar", q:"Wednesday は 何曜日？", c:["水曜日", "火曜日", "木曜日", "金曜日"], a:0, kw:"Wednesday", em:"📅", yomi:"ウェンズデイ", rel:[], exp:"水曜日。d は読まない。"},
  {lv:7, stage:"calendar", q:"Thursday は 何曜日？", c:["木曜日", "火曜日", "水曜日", "土曜日"], a:0, kw:"Thursday", em:"📅", yomi:"サーズデイ", rel:[], exp:"木曜日。"},
  {lv:7, stage:"calendar", q:"Friday は 何曜日？", c:["金曜日", "木曜日", "土曜日", "月曜日"], a:0, kw:"Friday", em:"📅", yomi:"フライデイ", rel:[], exp:"金曜日。"},
  {lv:7, stage:"calendar", q:"Saturday は 何曜日？", c:["土曜日", "日曜日", "金曜日", "水曜日"], a:0, kw:"Saturday", em:"📅", yomi:"サタデイ", rel:[], exp:"土曜日。"},
  {lv:7, stage:"calendar", q:"January は 何月？", c:["1月", "2月", "6月", "7月"], a:0, kw:"January", em:"🗓️", yomi:"ジャニュアリー", rel:[], exp:"1月。"},
  {lv:7, stage:"calendar", q:"February は 何月？", c:["2月", "1月", "4月", "9月"], a:0, kw:"February", em:"🗓️", yomi:"フェブラリー", rel:[], exp:"2月。"},
  {lv:7, stage:"calendar", q:"March は 何月？", c:["3月", "5月", "4月", "8月"], a:0, kw:"March", em:"🗓️", yomi:"マーチ", rel:[], exp:"3月。"},
  {lv:7, stage:"calendar", q:"April は 何月？", c:["4月", "8月", "3月", "5月"], a:0, kw:"April", em:"🗓️", yomi:"エイプリル", rel:[], exp:"4月。"},
  {lv:7, stage:"calendar", q:"May は 何月？", c:["5月", "3月", "7月", "9月"], a:0, kw:"May", em:"🗓️", yomi:"メイ", rel:[], exp:"5月。"},
  {lv:7, stage:"calendar", q:"June は 何月？", c:["6月", "7月", "1月", "5月"], a:0, kw:"June", em:"🗓️", yomi:"ジューン", rel:[], exp:"6月。"},
  {lv:7, stage:"calendar", q:"July は 何月？", c:["7月", "6月", "1月", "10月"], a:0, kw:"July", em:"🗓️", yomi:"ジュライ", rel:[], exp:"7月。"},
  {lv:7, stage:"calendar", q:"August は 何月？", c:["8月", "4月", "10月", "12月"], a:0, kw:"August", em:"🗓️", yomi:"オーガスト", rel:[], exp:"8月。"},
  {lv:7, stage:"calendar", q:"September は 何月？", c:["9月", "11月", "7月", "12月"], a:0, kw:"September", em:"🗓️", yomi:"セプテンバー", rel:[], exp:"9月。"},
  {lv:7, stage:"calendar", q:"October は 何月？", c:["10月", "8月", "12月", "9月"], a:0, kw:"October", em:"🗓️", yomi:"オクトーバー", rel:[], exp:"10月。"},
  {lv:7, stage:"calendar", q:"November は 何月？", c:["11月", "9月", "12月", "10月"], a:0, kw:"November", em:"🗓️", yomi:"ノヴェンバー", rel:[], exp:"11月。"},
  {lv:7, stage:"calendar", q:"December は 何月？", c:["12月", "10月", "11月", "1月"], a:0, kw:"December", em:"🗓️", yomi:"ディセンバー", rel:[], exp:"12月。"},
  {lv:7, stage:"calendar", q:"sunny の 意味は？", c:["はれ", "あめ", "くもり", "ゆき"], a:0, kw:"sunny", em:"☀️", yomi:"サニー", rel:[], exp:"晴れ。"},
  {lv:7, stage:"calendar", q:"rainy の 意味は？", c:["あめ", "はれ", "ゆき", "かぜ"], a:0, kw:"rainy", em:"🌧️", yomi:"レイニー", rel:[], exp:"雨。"},
  {lv:7, stage:"calendar", q:"cloudy の 意味は？", c:["くもり", "はれ", "あめ", "ゆき"], a:0, kw:"cloudy", em:"☁️", yomi:"クラウディ", rel:[], exp:"くもり。"},
  {lv:7, stage:"calendar", q:"snowy の 意味は？", c:["ゆき", "あめ", "はれ", "くもり"], a:0, kw:"snowy", em:"❄️", yomi:"スノーウィ", rel:[], exp:"雪。"},
  {lv:7, stage:"calendar", q:"「かぜが強い」は 英語で？", c:["windy", "sunny", "rainy", "cloudy"], a:0, kw:"windy", em:"🌬️", yomi:"ウィンディ", rel:[], exp:"風が強いは windy。"},
  {lv:7, stage:"calendar", q:"「あつい」天気は 英語で？", c:["hot", "cold", "cool", "warm"], a:0, kw:"hot", em:"🥵", yomi:"ホット", rel:[], exp:"暑いは hot。"},
  {lv:7, stage:"calendar", q:"「さむい」天気は 英語で？", c:["cold", "hot", "warm", "dry"], a:0, kw:"cold", em:"🥶", yomi:"コールド", rel:[], exp:"寒いは cold。"},
  {lv:7, stage:"calendar", q:"spring の 意味は？", c:["はる", "なつ", "あき", "ふゆ"], a:0, kw:"spring", em:"🌸", yomi:"スプリング", rel:[], exp:"春。"},
  {lv:7, stage:"calendar", q:"summer の 意味は？", c:["なつ", "はる", "ふゆ", "あき"], a:0, kw:"summer", em:"🌻", yomi:"サマー", rel:[], exp:"夏。"},
  {lv:7, stage:"calendar", q:"fall（autumn）の 意味は？", c:["あき", "はる", "なつ", "ふゆ"], a:0, kw:"fall", em:"🍁", yomi:"フォール", rel:[], exp:"秋。autumn ともいう。"},
  {lv:7, stage:"calendar", q:"winter の 意味は？", c:["ふゆ", "なつ", "はる", "あき"], a:0, kw:"winter", em:"⛄", yomi:"ウィンター", rel:[], exp:"冬。"},

  // ===== Lv8  学習8 たずねる言葉 =====
  {lv:8, stage:"wh", q:"「なに？」= ___ is this?", c:["What", "Who", "Where", "When"], a:0, kw:"what", em:"❓", yomi:"ワット", rel:[], exp:"What は「何」。"},
  {lv:8, stage:"wh", q:"「だれ？」= ___ is she?", c:["Who", "What", "Where", "Why"], a:0, kw:"who", em:"🧑", yomi:"フー", rel:[], exp:"Who は「だれ」。"},
  {lv:8, stage:"wh", q:"「どこ？」= ___ do you live?", c:["Where", "When", "What", "Who"], a:0, kw:"where", em:"📍", yomi:"ウェア", rel:[], exp:"Where は「どこ」。"},
  {lv:8, stage:"wh", q:"「いつ？」= ___ is your birthday?", c:["When", "Where", "Why", "Which"], a:0, kw:"when", em:"🎂", yomi:"ウェン", rel:[], exp:"When は「いつ」。"},
  {lv:8, stage:"wh", q:"「なぜ？」= ___ are you happy?", c:["Why", "How", "Who", "What"], a:0, kw:"why", em:"🤔", yomi:"ワイ", rel:[], exp:"Why は「なぜ」。"},
  {lv:8, stage:"wh", q:"「どうやって／どんな？」= ___ are you?", c:["How", "Why", "What", "When"], a:0, kw:"how", em:"💭", yomi:"ハウ", rel:[], exp:"How は「どのように・どんな」。"},
  {lv:8, stage:"wh", q:"「どっち？」= ___ do you want, tea or milk?", c:["Which", "What", "Who", "Where"], a:0, kw:"which", em:"🔀", yomi:"ウィッチ", rel:[], exp:"Which は「どちら」。"},
  {lv:8, stage:"wh", q:"「だれの？」= ___ bag is this?", c:["Whose", "Who", "Which", "What"], a:0, kw:"whose", em:"🎒", yomi:"フーズ", rel:[], exp:"Whose は「だれの」。"},
  {lv:8, stage:"wh", q:"How many …? は 何を たずねる？", c:["数", "色", "値段", "時間"], a:0, kw:"how many", em:"🔢", rel:[], exp:"How many で数をたずねる。"},
  {lv:8, stage:"wh", q:"How much …? は 何を たずねる？", c:["値段・量", "数", "場所", "年齢"], a:0, kw:"how much", em:"💰", rel:[], exp:"How much で値段・量をたずねる。"},
  {lv:8, stage:"wh", q:"How old …? は 何を たずねる？", c:["年齢", "身長", "時間", "数"], a:0, kw:"how old", em:"🎂", rel:[], exp:"How old で年齢をたずねる。"},
  {lv:8, stage:"wh", q:"What time …? は 何を たずねる？", c:["時刻", "場所", "理由", "色"], a:0, kw:"what time", em:"🕐", rel:[], exp:"What time で時刻をたずねる。"},
  {lv:8, stage:"wh", q:"What color …? は 何を たずねる？", c:["色", "数", "場所", "時間"], a:0, kw:"what color", em:"🎨", rel:[], exp:"What color で色をたずねる。"},
  {lv:8, stage:"wh", q:"How long …? は 何を たずねる？", c:["長さ・時間", "色", "数", "名前"], a:0, kw:"how long", em:"📏", rel:[], exp:"How long で長さ・時間をたずねる。"},
  {lv:8, stage:"prep", q:"「箱の 中に」= ___ the box", c:["in", "on", "under", "to"], a:0, kw:"in", em:"📦", yomi:"イン", rel:[], exp:"「中に」は in。"},
  {lv:8, stage:"prep", q:"「机の 上に」= ___ the desk", c:["on", "in", "under", "by"], a:0, kw:"on", em:"🔼", yomi:"オン", rel:[], exp:"接した「上に」は on。"},
  {lv:8, stage:"prep", q:"「いすの 下に」= ___ the chair", c:["under", "on", "in", "by"], a:0, kw:"under", em:"🔽", yomi:"アンダー", rel:[], exp:"「下に」は under。"},
  {lv:8, stage:"prep", q:"「ドアの そばに」= ___ the door", c:["by", "in", "on", "to"], a:0, kw:"by", em:"🚪", yomi:"バイ", rel:[], exp:"「そばに」は by。"},
  {lv:8, stage:"prep", q:"「学校へ 行く」= go ___ school", c:["to", "in", "on", "at"], a:0, kw:"to", em:"🏫", yomi:"トゥー", rel:[], exp:"方向・行き先は to。"},
  {lv:8, stage:"prep", q:"「7時に」= ___ seven o'clock", c:["at", "in", "on", "to"], a:0, kw:"at", em:"🕖", yomi:"アット", rel:[], exp:"時刻の前は at。"},
  {lv:8, stage:"prep", q:"「駅の 近くに」= ___ the station", c:["near", "on", "in", "to"], a:0, kw:"near", em:"🚉", yomi:"ニア", rel:[], exp:"「近くに」は near。"},
  {lv:8, stage:"prep", q:"「家の 前に」= ___ the house", c:["in front of", "behind", "near", "on"], a:0, kw:"in front of", em:"🏠", yomi:"インフロントオブ", rel:[], exp:"「〜の前に」は in front of。"},
  {lv:8, stage:"prep", q:"「木の 後ろに」= ___ the tree", c:["behind", "in front of", "under", "by"], a:0, kw:"behind", em:"🌳", yomi:"ビハインド", rel:[], exp:"「〜の後ろに」は behind。"},
  {lv:8, stage:"prep", q:"「AとBの 間に」= ___ A and B", c:["between", "among", "near", "by"], a:0, kw:"between", em:"↔️", yomi:"ビトウィーン", rel:[], exp:"2つの「間に」は between。"},
  {lv:8, stage:"prep", q:"「学校の となりに」= ___ the school", c:["next to", "on", "in", "to"], a:0, kw:"next to", em:"🏫", yomi:"ネクストトゥ", rel:[], exp:"「〜のとなりに」は next to。"},
  {lv:8, stage:"prep", q:"「テーブルの 上方に（はなれて）」= ___ the table", c:["over", "under", "in", "by"], a:0, kw:"over", em:"🔝", yomi:"オーバー", rel:[], exp:"はなれた「上方に」は over。"},
  {lv:8, stage:"prep", q:"「部屋の 中へ 入る」= go ___ the room", c:["into", "on", "at", "by"], a:0, kw:"into", em:"🚪", yomi:"イントゥ", rel:[], exp:"「〜の中へ」は into。"},
  {lv:8, stage:"prep", q:"「東京から」= ___ Tokyo", c:["from", "to", "at", "in"], a:0, kw:"from", em:"🗾", yomi:"フロム", rel:[], exp:"「〜から」は from。"},
  {lv:8, stage:"prep", q:"「友だちと 一緒に」= ___ my friends", c:["with", "of", "to", "at"], a:0, kw:"with", em:"👬", yomi:"ウィズ", rel:[], exp:"「〜と一緒に」は with。"},
  {lv:8, stage:"prep", q:"「木の まわりに」= ___ the tree", c:["around", "into", "from", "at"], a:0, kw:"around", em:"🔄", yomi:"アラウンド", rel:[], exp:"「〜のまわりに」は around。"},

  // ===== Lv9  英検5級 前編(単語) =====
  {lv:9, stage:"vocab", q:"school の 意味は？", c:["学校", "駅", "公園", "病院"], a:0, kw:"school", em:"🏫", yomi:"スクール", rel:[], exp:"school は 学校。"},
  {lv:9, stage:"vocab", q:"student の 意味は？", c:["生徒", "先生", "医者", "店員"], a:0, kw:"student", em:"🧑‍🎓", yomi:"ステューデント", rel:[], exp:"student は 生徒。"},
  {lv:9, stage:"vocab", q:"classroom の 意味は？", c:["教室", "台所", "寝室", "ふろ場"], a:0, kw:"classroom", em:"🚪", yomi:"クラスルーム", rel:[], exp:"classroom は 教室。"},
  {lv:9, stage:"vocab", q:"English の 意味は？", c:["英語", "国語", "算数", "理科"], a:0, kw:"English", em:"🔤", yomi:"イングリッシュ", rel:[], exp:"English は 英語。"},
  {lv:9, stage:"vocab", q:"math の 意味は？", c:["算数・数学", "音楽", "図工", "体育"], a:0, kw:"math", em:"➗", yomi:"マス", rel:[], exp:"math は 算数・数学。"},
  {lv:9, stage:"vocab", q:"science の 意味は？", c:["理科", "社会", "英語", "家庭科"], a:0, kw:"science", em:"🔬", yomi:"サイエンス", rel:[], exp:"science は 理科。"},
  {lv:9, stage:"vocab", q:"music の 意味は？", c:["音楽", "美術", "算数", "理科"], a:0, kw:"music", em:"🎵", yomi:"ミュージック", rel:[], exp:"music は 音楽。"},
  {lv:9, stage:"vocab", q:"「つくえ」は 英語で どれ？", c:["desk", "chair", "door", "box"], a:0, kw:"desk", em:"🪑", yomi:"デスク", rel:[], exp:"机は desk。"},
  {lv:9, stage:"vocab", q:"chair の 意味は？", c:["いす", "つくえ", "ドア", "まど"], a:0, kw:"chair", em:"💺", yomi:"チェア", rel:[], exp:"chair は いす。"},
  {lv:9, stage:"vocab", q:"notebook の 意味は？", c:["ノート", "教科書", "えんぴつ", "消しゴム"], a:0, kw:"notebook", em:"📓", yomi:"ノートブック", rel:[], exp:"notebook は ノート。"},
  {lv:9, stage:"vocab", q:"pencil の 意味は？", c:["えんぴつ", "ペン", "ノート", "定規"], a:0, kw:"pencil", em:"✏️", yomi:"ペンシル", rel:[], exp:"pencil は えんぴつ。"},
  {lv:9, stage:"vocab", q:"eraser の 意味は？", c:["消しゴム", "えんぴつ", "定規", "のり"], a:0, kw:"eraser", em:"🧽", yomi:"イレイサー", rel:[], exp:"eraser は 消しゴム。"},
  {lv:9, stage:"vocab", q:"homework の 意味は？", c:["宿題", "授業", "テスト", "質問"], a:0, kw:"homework", em:"📝", yomi:"ホームワーク", rel:[], exp:"homework は 宿題。"},
  {lv:9, stage:"vocab", q:"「教科書」は 英語で どれ？", c:["textbook", "notebook", "dictionary", "letter"], a:0, kw:"textbook", em:"📖", yomi:"テキストブック", rel:[], exp:"教科書は textbook。"},
  {lv:9, stage:"vocab", q:"station の 意味は？", c:["駅", "公園", "図書館", "病院"], a:0, kw:"station", em:"🚉", yomi:"ステーション", rel:[], exp:"station は 駅。"},
  {lv:9, stage:"vocab", q:"park の 意味は？", c:["公園", "駅", "店", "動物園"], a:0, kw:"park", em:"🏞️", yomi:"パーク", rel:[], exp:"park は 公園。"},
  {lv:9, stage:"vocab", q:"library の 意味は？", c:["図書館", "病院", "銀行", "郵便局"], a:0, kw:"library", em:"📚", yomi:"ライブラリー", rel:[], exp:"library は 図書館。"},
  {lv:9, stage:"vocab", q:"hospital の 意味は？", c:["病院", "図書館", "学校", "駅"], a:0, kw:"hospital", em:"🏥", yomi:"ホスピタル", rel:[], exp:"hospital は 病院。"},
  {lv:9, stage:"vocab", q:"zoo の 意味は？", c:["動物園", "公園", "水族館", "遊園地"], a:0, kw:"zoo", em:"🦁", yomi:"ズー", rel:[], exp:"zoo は 動物園。"},
  {lv:9, stage:"vocab", q:"「お店」は 英語で どれ？", c:["store", "school", "park", "zoo"], a:0, kw:"store", em:"🏪", yomi:"ストア", rel:[], exp:"店は store（shop）。"},
  {lv:9, stage:"vocab", q:"restaurant の 意味は？", c:["レストラン", "病院", "図書館", "駅"], a:0, kw:"restaurant", em:"🍽️", yomi:"レストラン", rel:[], exp:"restaurant は レストラン。"},
  {lv:9, stage:"vocab", q:"「家」は 英語で どれ？", c:["house", "room", "door", "garden"], a:0, kw:"house", em:"🏠", yomi:"ハウス", rel:[], exp:"家は house。"},
  {lv:9, stage:"vocab", q:"room の 意味は？", c:["部屋", "台所", "庭", "屋根"], a:0, kw:"room", em:"🚪", yomi:"ルーム", rel:[], exp:"room は 部屋。"},
  {lv:9, stage:"vocab", q:"kitchen の 意味は？", c:["台所", "寝室", "ふろ場", "居間"], a:0, kw:"kitchen", em:"🍳", yomi:"キッチン", rel:[], exp:"kitchen は 台所。"},
  {lv:9, stage:"vocab", q:"bank の 意味は？", c:["銀行", "郵便局", "病院", "店"], a:0, kw:"bank", em:"🏦", yomi:"バンク", rel:[], exp:"bank は 銀行。"},
  {lv:9, stage:"vocab", q:"「郵便局」は 英語で どれ？", c:["post office", "bank", "station", "library"], a:0, kw:"post office", em:"📮", yomi:"ポスト オフィス", rel:[], exp:"郵便局は post office。"},
  {lv:9, stage:"vocab", q:"doctor の 意味は？", c:["医者", "先生", "看護師", "店員"], a:0, kw:"doctor", em:"🧑‍⚕️", yomi:"ドクター", rel:[], exp:"doctor は 医者。"},
  {lv:9, stage:"vocab", q:"nurse の 意味は？", c:["看護師", "医者", "先生", "コック"], a:0, kw:"nurse", em:"👩‍⚕️", yomi:"ナース", rel:[], exp:"nurse は 看護師。"},
  {lv:9, stage:"vocab", q:"「料理人・コック」は 英語で どれ？", c:["cook", "farmer", "driver", "singer"], a:0, kw:"cook", em:"🧑‍🍳", yomi:"クック", rel:[], exp:"料理人は cook。"},
  {lv:9, stage:"vocab", q:"farmer の 意味は？", c:["農家", "漁師", "コック", "歌手"], a:0, kw:"farmer", em:"🧑‍🌾", yomi:"ファーマー", rel:[], exp:"farmer は 農家。"},
  {lv:9, stage:"vocab", q:"singer の 意味は？", c:["歌手", "ダンサー", "画家", "作家"], a:0, kw:"singer", em:"🎤", yomi:"シンガー", rel:[], exp:"singer は 歌手。"},
  {lv:9, stage:"vocab", q:"pilot の 意味は？", c:["パイロット", "運転手", "船長", "医者"], a:0, kw:"pilot", em:"🧑‍✈️", yomi:"パイロット", rel:[], exp:"pilot は パイロット。"},
  {lv:9, stage:"vocab", q:"「運転手」は 英語で どれ？", c:["driver", "pilot", "farmer", "cook"], a:0, kw:"driver", em:"🚗", yomi:"ドライバー", rel:[], exp:"運転手は driver。"},
  {lv:9, stage:"vocab", q:"police officer の 意味は？", c:["警察官", "消防士", "医者", "先生"], a:0, kw:"police officer", em:"👮", yomi:"ポリス オフィサー", rel:[], exp:"police officer は 警察官。"},
  {lv:9, stage:"vocab", q:"dancer の 意味は？", c:["ダンサー", "歌手", "画家", "作家"], a:0, kw:"dancer", em:"💃", yomi:"ダンサー", rel:[], exp:"dancer は ダンサー。"},
  {lv:9, stage:"vocab", q:"dentist の 意味は？", c:["歯医者", "医者", "看護師", "先生"], a:0, kw:"dentist", em:"🦷", yomi:"デンティスト", rel:[], exp:"dentist は 歯医者。"},
  {lv:9, stage:"vocab", q:"soccer の 意味は？", c:["サッカー", "野球", "テニス", "水泳"], a:0, kw:"soccer", em:"⚽", yomi:"サッカー", rel:[], exp:"soccer は サッカー。"},
  {lv:9, stage:"vocab", q:"baseball の 意味は？", c:["野球", "サッカー", "バスケ", "バレー"], a:0, kw:"baseball", em:"⚾", yomi:"ベースボール", rel:[], exp:"baseball は 野球。"},
  {lv:9, stage:"vocab", q:"tennis の 意味は？", c:["テニス", "卓球", "バドミントン", "野球"], a:0, kw:"tennis", em:"🎾", yomi:"テニス", rel:[], exp:"tennis は テニス。"},
  {lv:9, stage:"vocab", q:"basketball の 意味は？", c:["バスケットボール", "バレーボール", "野球", "サッカー"], a:0, kw:"basketball", em:"🏀", yomi:"バスケットボール", rel:[], exp:"basketball は バスケットボール。"},
  {lv:9, stage:"vocab", q:"「バレーボール」は 英語で どれ？", c:["volleyball", "basketball", "baseball", "soccer"], a:0, kw:"volleyball", em:"🏐", yomi:"バレーボール", rel:[], exp:"バレーボールは volleyball。"},
  {lv:9, stage:"vocab", q:"swimming の 意味は？", c:["水泳", "スキー", "スケート", "登山"], a:0, kw:"swimming", em:"🏊", yomi:"スイミング", rel:[], exp:"swimming は 水泳。"},
  {lv:9, stage:"vocab", q:"「スキー」は 英語で どれ？", c:["skiing", "skating", "swimming", "running"], a:0, kw:"skiing", em:"⛷️", yomi:"スキーイング", rel:[], exp:"スキーは skiing。"},
  {lv:9, stage:"vocab", q:"game の 意味は？", c:["ゲーム・試合", "遊び", "スポーツ", "勝負"], a:0, kw:"game", em:"🎮", yomi:"ゲーム", rel:[], exp:"game は ゲーム・試合。"},
  {lv:9, stage:"vocab", q:"juice の 意味は？", c:["ジュース", "水", "牛乳", "お茶"], a:0, kw:"juice", em:"🧃", yomi:"ジュース", rel:[], exp:"juice は ジュース。"},
  {lv:9, stage:"vocab", q:"「お茶」は 英語で どれ？", c:["tea", "coffee", "juice", "milk"], a:0, kw:"tea", em:"🍵", yomi:"ティー", rel:[], exp:"お茶は tea。"},
  {lv:9, stage:"vocab", q:"coffee の 意味は？", c:["コーヒー", "お茶", "ジュース", "水"], a:0, kw:"coffee", em:"☕", yomi:"コーヒー", rel:[], exp:"coffee は コーヒー。"},
  {lv:9, stage:"vocab", q:"cake の 意味は？", c:["ケーキ", "クッキー", "アイス", "あめ"], a:0, kw:"cake", em:"🍰", yomi:"ケイク", rel:[], exp:"cake は ケーキ。"},
  {lv:9, stage:"vocab", q:"「クッキー」は 英語で どれ？", c:["cookie", "cake", "candy", "bread"], a:0, kw:"cookie", em:"🍪", yomi:"クッキー", rel:[], exp:"クッキーは cookie。"},
  {lv:9, stage:"vocab", q:"candy の 意味は？", c:["あめ・キャンディ", "ケーキ", "ガム", "チョコ"], a:0, kw:"candy", em:"🍬", yomi:"キャンディ", rel:[], exp:"candy は あめ。"},
  {lv:9, stage:"vocab", q:"ice cream の 意味は？", c:["アイスクリーム", "ケーキ", "ゼリー", "プリン"], a:0, kw:"ice cream", em:"🍦", yomi:"アイスクリーム", rel:[], exp:"ice cream は アイスクリーム。"},
  {lv:9, stage:"vocab", q:"「サラダ」は 英語で どれ？", c:["salad", "soup", "pizza", "curry"], a:0, kw:"salad", em:"🥗", yomi:"サラダ", rel:[], exp:"サラダは salad。"},
  {lv:9, stage:"vocab", q:"soup の 意味は？", c:["スープ", "サラダ", "カレー", "パン"], a:0, kw:"soup", em:"🍲", yomi:"スープ", rel:[], exp:"soup は スープ。"},
  {lv:9, stage:"vocab", q:"fruit の 意味は？", c:["くだもの", "やさい", "肉", "魚"], a:0, kw:"fruit", em:"🍓", yomi:"フルーツ", rel:[], exp:"fruit は くだもの。"},
  {lv:9, stage:"vocab", q:"vegetable の 意味は？", c:["やさい", "くだもの", "肉", "魚"], a:0, kw:"vegetable", em:"🥦", yomi:"ベジタブル", rel:[], exp:"vegetable は やさい。"},
  {lv:9, stage:"vocab", q:"lunch の 意味は？", c:["昼ごはん", "朝ごはん", "夜ごはん", "おやつ"], a:0, kw:"lunch", em:"🍱", yomi:"ランチ", rel:["breakfast", "dinner"], exp:"lunch は 昼ごはん。"},
  {lv:9, stage:"vocab", q:"bag の 意味は？", c:["かばん", "はこ", "ぼうし", "くつ"], a:0, kw:"bag", em:"🎒", yomi:"バッグ", rel:[], exp:"bag は かばん。"},
  {lv:9, stage:"vocab", q:"「はこ」は 英語で どれ？", c:["box", "bag", "cup", "cap"], a:0, kw:"box", em:"📦", yomi:"ボックス", rel:[], exp:"箱は box。"},
  {lv:9, stage:"vocab", q:"cap の 意味は？", c:["ぼうし", "くつ", "かばん", "てぶくろ"], a:0, kw:"cap", em:"🧢", yomi:"キャップ", rel:[], exp:"cap は ぼうし。"},
  {lv:9, stage:"vocab", q:"「うでどけい」は 英語で どれ？", c:["watch", "clock", "camera", "phone"], a:0, kw:"watch", em:"⌚", yomi:"ウォッチ", rel:[], exp:"うで時計は watch。"},
  {lv:9, stage:"vocab", q:"clock の 意味は？", c:["時計", "カレンダー", "カメラ", "テレビ"], a:0, kw:"clock", em:"🕐", yomi:"クロック", rel:[], exp:"clock は (置き・かけ)時計。"},
  {lv:9, stage:"vocab", q:"umbrella の 意味は？", c:["かさ", "ぼうし", "かばん", "くつ"], a:0, kw:"umbrella", em:"☂️", yomi:"アンブレラ", rel:[], exp:"umbrella は かさ。"},
  {lv:9, stage:"vocab", q:"camera の 意味は？", c:["カメラ", "テレビ", "時計", "電話"], a:0, kw:"camera", em:"📷", yomi:"カメラ", rel:[], exp:"camera は カメラ。"},
  {lv:9, stage:"vocab", q:"computer の 意味は？", c:["コンピューター", "テレビ", "電話", "ラジオ"], a:0, kw:"computer", em:"💻", yomi:"コンピューター", rel:[], exp:"computer は コンピューター。"},
  {lv:9, stage:"vocab", q:"「自転車」は 英語で どれ？", c:["bike", "car", "bus", "train"], a:0, kw:"bike", em:"🚲", yomi:"バイク", rel:["bicycle"], exp:"自転車は bike（bicycle）。"},
  {lv:9, stage:"vocab", q:"car の 意味は？", c:["車", "自転車", "バス", "電車"], a:0, kw:"car", em:"🚗", yomi:"カー", rel:[], exp:"car は 車。"},
  {lv:9, stage:"vocab", q:"ball の 意味は？", c:["ボール", "バット", "グローブ", "ラケット"], a:0, kw:"ball", em:"🥎", yomi:"ボール", rel:[], exp:"ball は ボール。"},
  {lv:9, stage:"vocab", q:"「かぎ」は 英語で どれ？", c:["key", "cup", "pen", "ball"], a:0, kw:"key", em:"🔑", yomi:"キー", rel:[], exp:"かぎは key。"},
  {lv:9, stage:"vocab", q:"letter の 意味は？", c:["手紙", "はがき", "切手", "新聞"], a:0, kw:"letter", em:"✉️", yomi:"レター", rel:[], exp:"letter は 手紙（文字の意味も）。"},
  {lv:9, stage:"vocab", q:"sky の 意味は？", c:["空", "海", "山", "川"], a:0, kw:"sky", em:"🌤️", yomi:"スカイ", rel:[], exp:"sky は 空。"},
  {lv:9, stage:"vocab", q:"「海」は 英語で どれ？", c:["sea", "sky", "river", "lake"], a:0, kw:"sea", em:"🌊", yomi:"スィー", rel:[], exp:"海は sea。"},
  {lv:9, stage:"vocab", q:"mountain の 意味は？", c:["山", "川", "海", "森"], a:0, kw:"mountain", em:"⛰️", yomi:"マウンテン", rel:[], exp:"mountain は 山。"},
  {lv:9, stage:"vocab", q:"river の 意味は？", c:["川", "海", "山", "湖"], a:0, kw:"river", em:"🏞️", yomi:"リバー", rel:[], exp:"river は 川。"},
  {lv:9, stage:"vocab", q:"flower の 意味は？", c:["花", "木", "草", "葉"], a:0, kw:"flower", em:"🌸", yomi:"フラワー", rel:[], exp:"flower は 花。"},
  {lv:9, stage:"vocab", q:"tree の 意味は？", c:["木", "花", "草", "森"], a:0, kw:"tree", em:"🌳", yomi:"トゥリー", rel:[], exp:"tree は 木。"},
  {lv:9, stage:"vocab", q:"moon の 意味は？", c:["月", "星", "太陽", "空"], a:0, kw:"moon", em:"🌙", yomi:"ムーン", rel:[], exp:"moon は 月。"},
  {lv:9, stage:"vocab", q:"sun の 意味は？", c:["太陽", "月", "星", "雲"], a:0, kw:"sun", em:"☀️", yomi:"サン", rel:[], exp:"sun は 太陽。"},
  {lv:9, stage:"vocab", q:"want の 意味は？", c:["ほしい", "必要とする", "持っている", "あげる"], a:0, kw:"want", em:"🙏", yomi:"ウォント", rel:[], exp:"want は ほしい。"},
  {lv:9, stage:"vocab", q:"need の 意味は？", c:["必要とする", "ほしがる", "使う", "買う"], a:0, kw:"need", em:"❗", yomi:"ニード", rel:[], exp:"need は 必要とする。"},
  {lv:9, stage:"vocab", q:"「使う」は 英語で どれ？", c:["use", "make", "buy", "sell"], a:0, kw:"use", em:"🔧", yomi:"ユーズ", rel:[], exp:"使うは use。"},
  {lv:9, stage:"vocab", q:"buy の 意味は？", c:["買う", "売る", "使う", "作る"], a:0, kw:"buy", em:"🛒", yomi:"バイ", rel:[], exp:"buy は 買う。"},
  {lv:9, stage:"vocab", q:"help の 意味は？", c:["助ける・手伝う", "こわす", "かくす", "運ぶ"], a:0, kw:"help", em:"🤝", yomi:"ヘルプ", rel:[], exp:"help は 助ける・手伝う。"},
  {lv:9, stage:"vocab", q:"「そうじする」は 英語で どれ？", c:["clean", "wash", "cook", "help"], a:0, kw:"clean", em:"🧹", yomi:"クリーン", rel:[], exp:"そうじするは clean。"},
  {lv:9, stage:"vocab", q:"wash の 意味は？", c:["あらう", "ふく", "みがく", "そうじする"], a:0, kw:"wash", em:"🚿", yomi:"ウォッシュ", rel:[], exp:"wash は あらう。"},
  {lv:9, stage:"vocab", q:"enjoy の 意味は？", c:["楽しむ", "つかれる", "いそぐ", "まつ"], a:0, kw:"enjoy", em:"😊", yomi:"エンジョイ", rel:[], exp:"enjoy は 楽しむ。"},
  {lv:9, stage:"vocab", q:"「教える」は 英語で どれ？", c:["teach", "learn", "speak", "read"], a:0, kw:"teach", em:"🧑‍🏫", yomi:"ティーチ", rel:[], exp:"教えるは teach。"},
  {lv:9, stage:"vocab", q:"speak の 意味は？", c:["話す", "聞く", "読む", "書く"], a:0, kw:"speak", em:"🗣️", yomi:"スピーク", rel:[], exp:"speak は 話す。"},
  {lv:9, stage:"vocab", q:"meet の 意味は？", c:["会う", "訪ねる", "呼ぶ", "知る"], a:0, kw:"meet", em:"🤝", yomi:"ミート", rel:[], exp:"meet は 会う。"},
  {lv:9, stage:"vocab", q:"visit の 意味は？", c:["訪ねる", "会う", "招く", "住む"], a:0, kw:"visit", em:"🧳", yomi:"ヴィジット", rel:[], exp:"visit は 訪ねる。"},
  {lv:9, stage:"vocab", q:"tall の 意味は？", c:["背が高い", "背が低い", "大きい", "小さい"], a:0, kw:"tall", em:"📏", yomi:"トール", rel:[], exp:"tall は 背が高い。"},
  {lv:9, stage:"vocab", q:"「若い」は 英語で どれ？", c:["young", "old", "tall", "kind"], a:0, kw:"young", em:"👶", yomi:"ヤング", rel:[], exp:"若いは young。"},
  {lv:9, stage:"vocab", q:"kind の 意味は？", c:["親切な", "こわい", "つよい", "かわいい"], a:0, kw:"kind", em:"😇", yomi:"カインド", rel:[], exp:"kind は 親切な。"},
  {lv:9, stage:"vocab", q:"「かわいい」は 英語で どれ？", c:["cute", "ugly", "big", "small"], a:0, kw:"cute", em:"🥰", yomi:"キュート", rel:[], exp:"かわいいは cute。"},
  {lv:9, stage:"vocab", q:"easy の 意味は？", c:["かんたんな", "むずかしい", "いそがしい", "つよい"], a:0, kw:"easy", em:"✅", yomi:"イージー", rel:[], exp:"easy は かんたんな。"},
  {lv:9, stage:"vocab", q:"「むずかしい」は 英語で どれ？", c:["difficult", "easy", "cheap", "heavy"], a:0, kw:"difficult", em:"😓", yomi:"ディフィカルト", rel:[], exp:"むずかしいは difficult。"},
  {lv:9, stage:"vocab", q:"busy の 意味は？", c:["いそがしい", "ひまな", "ねむい", "つかれた"], a:0, kw:"busy", em:"🏃", yomi:"ビジー", rel:[], exp:"busy は いそがしい。"},
  {lv:9, stage:"vocab", q:"hungry の 意味は？", c:["おなかがすいた", "のどがかわいた", "ねむい", "つかれた"], a:0, kw:"hungry", em:"🍽️", yomi:"ハングリー", rel:[], exp:"hungry は おなかがすいた。"},
  {lv:9, stage:"vocab", q:"「のどがかわいた」は 英語で どれ？", c:["thirsty", "hungry", "sleepy", "tired"], a:0, kw:"thirsty", em:"🥤", yomi:"サースティ", rel:[], exp:"のどがかわいたは thirsty。"},
  {lv:9, stage:"vocab", q:"tired の 意味は？", c:["つかれた", "げんきな", "ねむい", "いそがしい"], a:0, kw:"tired", em:"😫", yomi:"タイアード", rel:[], exp:"tired は つかれた。"},
  {lv:9, stage:"vocab", q:"favorite の 意味は？", c:["お気に入りの", "きらいな", "あたらしい", "ふるい"], a:0, kw:"favorite", em:"⭐", yomi:"フェイバリット", rel:[], exp:"favorite は お気に入りの。"},

  // ===== Lv10  英検5級 後編(文章) =====
  {lv:10, stage:"fill", q:"I ___ a student.", c:["am", "is", "are", "do"], a:0, kw:"be動詞", em:"🧑‍🎓", yaku:"わたしは生徒です。", rel:[], exp:"I には am。"},
  {lv:10, stage:"fill", q:"She ___ tennis every day.", c:["plays", "play", "playing", "played"], a:0, kw:"三単現", em:"🎾", yaku:"彼女は毎日テニスをします。", rel:[], exp:"3人称単数は plays。"},
  {lv:10, stage:"fill", q:"He ___ to school by bike.", c:["goes", "go", "going", "does"], a:0, kw:"三単現", em:"🚲", yaku:"彼は自転車で学校へ行きます。", rel:[], exp:"He なので goes。"},
  {lv:10, stage:"fill", q:"___ you like music?", c:["Do", "Does", "Are", "Is"], a:0, kw:"疑問文", em:"🎵", yaku:"あなたは音楽が好きですか。", rel:[], exp:"一般動詞の疑問は Do you〜?。"},
  {lv:10, stage:"fill", q:"They ___ my friends.", c:["are", "is", "am", "does"], a:0, kw:"be動詞", em:"👬", yaku:"彼らはわたしの友だちです。", rel:[], exp:"複数は are。"},
  {lv:10, stage:"fill", q:"This is ___ apple.", c:["an", "a", "the", "some"], a:0, kw:"a/an", em:"🍎", yaku:"これはりんごです。", rel:[], exp:"母音の音の前は an。"},
  {lv:10, stage:"fill", q:"I have two ___.", c:["dogs", "dog", "doges", "a dog"], a:0, kw:"複数形", em:"🐶", yaku:"わたしは犬を2ひき飼っています。", rel:[], exp:"2つ以上は s。"},
  {lv:10, stage:"fill", q:"Can you ___? — Yes, I can.", c:["swim", "swims", "swimming", "swam"], a:0, kw:"can", em:"🏊", yaku:"泳げますか。—はい、泳げます。", rel:[], exp:"can のあとは動詞の原形。"},
  {lv:10, stage:"fill", q:"Look! The baby ___.", c:["is sleeping", "sleep", "sleeps", "sleeping"], a:0, kw:"現在進行形", em:"👶", yaku:"見て！赤ちゃんが眠っています。", rel:[], exp:"be+動詞ing。"},
  {lv:10, stage:"fill", q:"My birthday is ___ May.", c:["in", "on", "at", "to"], a:0, kw:"前置詞", em:"🎂", yaku:"わたしの誕生日は5月です。", rel:[], exp:"月の前は in。"},
  {lv:10, stage:"fill", q:"I'm hungry. Let's eat ___.", c:["lunch", "water", "music", "chairs"], a:0, kw:"語彙", em:"🍱", yaku:"おなかがすいた。昼ごはんを食べよう。", rel:[], exp:"food を選ぶ。"},
  {lv:10, stage:"fill", q:"It's cold. Close the ___.", c:["window", "book", "dog", "apple"], a:0, kw:"語彙", em:"🪟", yaku:"寒いね。窓を閉めて。", rel:[], exp:"閉めるのは window。"},
  {lv:10, stage:"fill", q:"I ___ my hands before lunch.", c:["wash", "read", "sing", "jump"], a:0, kw:"語彙", em:"🚿", yaku:"昼ごはんの前に手を洗います。", rel:[], exp:"手は wash する。"},
  {lv:10, stage:"fill", q:"My father is a ___. He works at a hospital.", c:["doctor", "teacher", "farmer", "cook"], a:0, kw:"語彙", em:"🧑‍⚕️", yaku:"父は医者です。病院で働いています。", rel:[], exp:"hospital で働くのは doctor。"},
  {lv:10, stage:"fill", q:"I go to the ___ to borrow books.", c:["library", "zoo", "sea", "station"], a:0, kw:"語彙", em:"📚", yaku:"本を借りに図書館へ行きます。", rel:[], exp:"本を借りる場所は library（図書館）。"},
  {lv:10, stage:"fill", q:"We play ___ with a ball and a bat.", c:["baseball", "tennis", "swimming", "skiing"], a:0, kw:"語彙", em:"⚾", yaku:"ボールとバットで野球をします。", rel:[], exp:"bat を使うのは baseball。"},
  {lv:10, stage:"fill", q:"I'm thirsty. I want some ___.", c:["juice", "bread", "pencils", "shoes"], a:0, kw:"語彙", em:"🧃", yaku:"のどがかわいた。ジュースがほしい。", rel:[], exp:"飲み物は juice。"},
  {lv:10, stage:"fill", q:"Please open your ___ to page ten.", c:["textbook", "umbrella", "camera", "cap"], a:0, kw:"語彙", em:"📖", yaku:"教科書の10ページを開いて。", rel:[], exp:"ページがあるのは textbook。"},
  {lv:10, stage:"fill", q:"Look at the ___ in the sky.", c:["moon", "fish", "desk", "car"], a:0, kw:"語彙", em:"🌙", yaku:"空の月を見て。", rel:[], exp:"空にあるのは moon。"},
  {lv:10, stage:"fill", q:"I study ___ at school. I like numbers.", c:["math", "music", "art", "P.E."], a:0, kw:"語彙", em:"➗", yaku:"学校で算数を勉強します。数字が好きです。", rel:[], exp:"numbers は math。"},
  {lv:10, stage:"fill", q:"She ___ not like natto.", c:["does", "do", "is", "are"], a:0, kw:"否定文", em:"🚫", yaku:"彼女は納豆が好きではありません。", rel:[], exp:"3人称単数の否定は does not。"},
  {lv:10, stage:"fill", q:"___ is that man? — He's my teacher.", c:["Who", "What", "Where", "When"], a:0, kw:"疑問詞", em:"🧑", yaku:"あの男の人はだれですか。—先生です。", rel:[], exp:"「だれ」は Who。"},
  {lv:10, stage:"fill", q:"___ do you live? — In Tokyo.", c:["Where", "When", "What", "Who"], a:0, kw:"疑問詞", em:"📍", yaku:"どこに住んでいますか。—東京です。", rel:[], exp:"「どこ」は Where。"},
  {lv:10, stage:"fill", q:"___ is your bag? — It's ten dollars.", c:["How much", "How many", "How old", "What time"], a:0, kw:"疑問詞", em:"💰", yaku:"かばんはいくらですか。—10ドルです。", rel:[], exp:"値段は How much。"},
  {lv:10, stage:"fill", q:"It ___ rainy today.", c:["is", "are", "am", "do"], a:0, kw:"be動詞", em:"🌧️", yaku:"今日は雨です。", rel:[], exp:"天気の主語 It は is。"},
  {lv:10, stage:"fill", q:"We ___ English on Monday.", c:["study", "studies", "are", "is"], a:0, kw:"一般動詞", em:"📘", yaku:"月曜日に英語を勉強します。", rel:[], exp:"複数は study。"},
  {lv:10, stage:"fill", q:"___ that your cat? — Yes, it is.", c:["Is", "Are", "Do", "Does"], a:0, kw:"疑問文", em:"🐱", yaku:"あれはあなたのねこですか。—はい。", rel:[], exp:"That の be動詞疑問は Is。"},
  {lv:10, stage:"fill", q:"There ___ five books on the desk.", c:["are", "is", "am", "be"], a:0, kw:"There", em:"📚", yaku:"机の上に本が5冊あります。", rel:[], exp:"複数は There are。"},
  {lv:10, stage:"fill", q:"I usually ___ up at six.", c:["get", "gets", "getting", "to get"], a:0, kw:"一般動詞", em:"⏰", yaku:"わたしはたいてい6時に起きます。", rel:[], exp:"主語 I なので get。"},
  {lv:10, stage:"fill", q:"He can ___ the piano well.", c:["play", "plays", "playing", "played"], a:0, kw:"can", em:"🎹", yaku:"彼はピアノが上手にひけます。", rel:[], exp:"can のあとは原形 play。"},
  {lv:10, stage:"fill", q:"Please ___ me. I can't open the door.", c:["help", "helps", "helping", "to help"], a:0, kw:"命令文", em:"🤝", yaku:"手伝って。ドアが開かない。", rel:[], exp:"命令文は原形 help。"},
  {lv:10, stage:"fill", q:"My sister ___ dinner every day.", c:["cooks", "cook", "cooking", "is"], a:0, kw:"三単現", em:"🍳", yaku:"姉は毎日夕食を作ります。", rel:[], exp:"3人称単数は cooks。"},
  {lv:10, stage:"fill", q:"Whose pen is this? — It's ___.", c:["mine", "my", "me", "I"], a:0, kw:"代名詞", em:"🖊️", yaku:"これはだれのペンですか。—わたしのです。", rel:[], exp:"「わたしのもの」は mine。"},
  {lv:10, stage:"fill", q:"I want a new ___. My old one is broken.", c:["watch", "milk", "rice", "water"], a:0, kw:"語彙", em:"⌚", yaku:"新しい時計がほしい。古いのはこわれた。", rel:[], exp:"壊れるのは watch。"},
  {lv:10, stage:"fill", q:"Let's ___ to the park.", c:["go", "goes", "going", "went"], a:0, kw:"Let's", em:"🏞️", yaku:"公園へ行こう。", rel:[], exp:"Let's のあとは原形 go。"},
  {lv:10, stage:"fill", q:"Tom and I ___ good friends.", c:["are", "am", "is", "be"], a:0, kw:"be動詞", em:"👬", yaku:"トムとわたしは仲の良い友だちです。", rel:[], exp:"主語が複数なので are。"},
  {lv:10, stage:"fill", q:"___ many pencils do you have?", c:["How", "What", "Who", "Which"], a:0, kw:"疑問詞", em:"✏️", yaku:"えんぴつを何本持っていますか。", rel:[], exp:"数は How many。"},
  {lv:10, stage:"fill", q:"I listen ___ music every day.", c:["to", "in", "on", "at"], a:0, kw:"前置詞", em:"🎵", yaku:"わたしは毎日音楽を聞きます。", rel:[], exp:"「listen to 〜」で「〜を聞く」。"},
  {lv:10, stage:"fill", q:"I read a ___ at home.", c:["book", "soccer", "cap", "zoo"], a:0, kw:"語彙", em:"📕", yaku:"家で本を読みます。", rel:[], exp:"読むのは book。"},
  {lv:10, stage:"fill", q:"She is ___ a letter now.", c:["writing", "write", "writes", "wrote"], a:0, kw:"現在進行形", em:"✍️", yaku:"彼女は今、手紙を書いています。", rel:[], exp:"be+動詞ing。"},
  {lv:10, stage:"dialog", q:"Girl: How are you?\nBoy: ( )", c:["I'm fine, thank you.", "Yes, I do.", "It's Monday.", "You're welcome."], a:0, kw:"あいさつ", em:"💬", yaku:"「元気ですか。」「元気です、ありがとう。」", rel:[], exp:"会話の流れに合う返事を選ぶ。"},
  {lv:10, stage:"dialog", q:"Boy: What time is it?\nGirl: ( )", c:["It's three o'clock.", "I'm eleven.", "It's sunny.", "Yes, please."], a:0, kw:"時間", em:"🕒", yaku:"「何時ですか。」「3時です。」", rel:[], exp:"会話の流れに合う返事を選ぶ。"},
  {lv:10, stage:"dialog", q:"Girl: Whose cap is this?\nBoy: ( )", c:["It's mine.", "I'm fine.", "Yes, it is.", "On Sunday."], a:0, kw:"だれの", em:"🧢", yaku:"「これはだれのぼうし。」「わたしのです。」", rel:[], exp:"会話の流れに合う返事を選ぶ。"},
  {lv:10, stage:"dialog", q:"Boy: Can you ski?\nGirl: ( )", c:["Yes, I can.", "It's a dog.", "I'm hungry.", "At school."], a:0, kw:"can", em:"⛷️", yaku:"「スキーはできる。」「はい、できます。」", rel:[], exp:"会話の流れに合う返事を選ぶ。"},
  {lv:10, stage:"dialog", q:"Girl: Let's play soccer.\nBoy: ( )", c:["Yes, let's!", "You're welcome.", "It's red.", "No, I'm not."], a:0, kw:"さそい", em:"⚽", yaku:"「サッカーしよう。」「うん、しよう！」", rel:[], exp:"会話の流れに合う返事を選ぶ。"},
  {lv:10, stage:"dialog", q:"Boy: What color do you like?\nGirl: ( )", c:["I like blue.", "It's Monday.", "Yes, I do.", "At home."], a:0, kw:"色", em:"🎨", yaku:"「何色が好き。」「青が好き。」", rel:[], exp:"会話の流れに合う返事を選ぶ。"},
  {lv:10, stage:"dialog", q:"Mother: Where is my bag?\nKen: ( )", c:["It's on the chair.", "I'm ten.", "It's rainy.", "Thank you."], a:0, kw:"場所", em:"🎒", yaku:"「わたしのかばんどこ。」「いすの上だよ。」", rel:[], exp:"会話の流れに合う返事を選ぶ。"},
  {lv:10, stage:"dialog", q:"Girl: Nice to meet you.\nBoy: ( )", c:["Nice to meet you, too.", "No, thank you.", "It's mine.", "See you."], a:0, kw:"あいさつ", em:"🤝", yaku:"「はじめまして。」「こちらこそ。」", rel:[], exp:"会話の流れに合う返事を選ぶ。"},
  {lv:10, stage:"dialog", q:"Teacher: What's your name?\nStudent: ( )", c:["My name is Emi.", "I'm fine.", "It's Monday.", "Yes, I do."], a:0, kw:"名前", em:"📛", yaku:"「お名前は。」「エミです。」", rel:[], exp:"会話の流れに合う返事を選ぶ。"},
  {lv:10, stage:"dialog", q:"Boy: How old are you?\nGirl: ( )", c:["I'm twelve.", "It's twelve.", "Yes, I am.", "On Monday."], a:0, kw:"年齢", em:"🎂", yaku:"「何歳。」「12歳です。」", rel:[], exp:"会話の流れに合う返事を選ぶ。"},
  {lv:10, stage:"dialog", q:"Girl: What do you want for your birthday?\nBoy: ( )", c:["I want a new bike.", "Yes, I do.", "It's blue.", "At six."], a:0, kw:"ほしい物", em:"🚲", yaku:"「誕生日に何がほしい。」「新しい自転車。」", rel:[], exp:"会話の流れに合う返事を選ぶ。"},
  {lv:10, stage:"dialog", q:"Boy: Do you like dogs?\nGirl: ( )", c:["Yes, I do.", "It's a dog.", "I'm fine.", "At home."], a:0, kw:"好み", em:"🐶", yaku:"「犬は好き。」「はい、好きです。」", rel:[], exp:"会話の流れに合う返事を選ぶ。"},
  {lv:10, stage:"dialog", q:"Girl: What day is it today?\nBoy: ( )", c:["It's Wednesday.", "It's three.", "It's sunny.", "Yes, I do."], a:0, kw:"曜日", em:"📅", yaku:"「今日は何曜日。」「水曜日です。」", rel:[], exp:"会話の流れに合う返事を選ぶ。"},
  {lv:10, stage:"dialog", q:"Mother: How's the weather?\nSon: ( )", c:["It's sunny.", "It's Monday.", "I'm fine.", "It's mine."], a:0, kw:"天気", em:"🌤️", yaku:"「天気はどう。」「晴れです。」", rel:[], exp:"会話の流れに合う返事を選ぶ。"},
  {lv:10, stage:"dialog", q:"Father: What time do you get up?\nEmi: ( )", c:["At six.", "It's six o'clock.", "Yes, I do.", "On Sunday."], a:0, kw:"時こく", em:"⏰", yaku:"「何時に起きる。」「6時です。」", rel:[], exp:"会話の流れに合う返事を選ぶ。"},
  {lv:10, stage:"dialog", q:"Boy: Where do you live?\nGirl: ( )", c:["I live in Osaka.", "It's Osaka.", "Yes, I do.", "At six."], a:0, kw:"場所", em:"🏠", yaku:"「どこに住んでる。」「大阪です。」", rel:[], exp:"会話の流れに合う返事を選ぶ。"},
  {lv:10, stage:"dialog", q:"Girl: What's this?\nBoy: ( )", c:["It's a camera.", "I'm fine.", "Yes, it is.", "At school."], a:0, kw:"これは何", em:"📷", yaku:"「これは何。」「カメラです。」", rel:[], exp:"会話の流れに合う返事を選ぶ。"},
  {lv:10, stage:"dialog", q:"Teacher: How many pens do you have?\nStudent: ( )", c:["I have five.", "It's five.", "Yes, I do.", "At five."], a:0, kw:"数", em:"🖊️", yaku:"「ペンを何本持ってる。」「5本です。」", rel:[], exp:"会話の流れに合う返事を選ぶ。"},
  {lv:10, stage:"dialog", q:"Emi: Happy birthday, Ken!\nKen: ( )", c:["Thank you!", "You're welcome.", "I'm sorry.", "See you."], a:0, kw:"お祝い", em:"🎂", yaku:"「お誕生日おめでとう、ケン！」「ありがとう！」", rel:[], exp:"会話の流れに合う返事を選ぶ。"},
  {lv:10, stage:"dialog", q:"Boy: See you tomorrow.\nGirl: ( )", c:["See you!", "Thank you.", "I'm fine.", "It's mine."], a:0, kw:"別れ", em:"👋", yaku:"「また明日。」「またね！」", rel:[], exp:"会話の流れに合う返事を選ぶ。"},
  {lv:10, stage:"dialog", q:"Girl: Thank you very much.\nBoy: ( )", c:["You're welcome.", "Here you are.", "I'm sorry.", "Me, too."], a:0, kw:"お礼", em:"🙏", yaku:"「どうもありがとう。」「どういたしまして。」", rel:[], exp:"会話の流れに合う返事を選ぶ。"},
  {lv:10, stage:"dialog", q:"Boy: Can I use your eraser?\nGirl: ( )", c:["Sure. Here you are.", "It's Monday.", "I'm hungry.", "At six."], a:0, kw:"依頼", em:"🧽", yaku:"「消しゴム借りていい。」「いいよ、どうぞ。」", rel:[], exp:"会話の流れに合う返事を選ぶ。"},
  {lv:10, stage:"dialog", q:"Mother: Would you like some milk?\nKen: ( )", c:["Yes, please.", "It's Sunday.", "I'm fine.", "At home."], a:0, kw:"すすめ", em:"🥛", yaku:"「牛乳いかが。」「はい、お願いします。」", rel:[], exp:"会話の流れに合う返事を選ぶ。"},
  {lv:10, stage:"dialog", q:"Boy: What subject do you like?\nGirl: ( )", c:["I like science.", "It's science.", "Yes, I do.", "At school."], a:0, kw:"教科", em:"🔬", yaku:"「好きな教科は。」「理科が好き。」", rel:[], exp:"会話の流れに合う返事を選ぶ。"},
  {lv:10, stage:"dialog", q:"Girl: Who is that boy?\nBoy: ( )", c:["He's my brother.", "It's mine.", "Yes, he is.", "At home."], a:0, kw:"だれ", em:"👦", yaku:"「あの男の子はだれ。」「わたしの弟です。」", rel:[], exp:"会話の流れに合う返事を選ぶ。"},
  {lv:10, stage:"dialog", q:"Boy: Is this your book?\nGirl: ( )", c:["No, it isn't.", "Yes, I do.", "It's Monday.", "At school."], a:0, kw:"確認", em:"📕", yaku:"「これはあなたの本。」「いいえ、ちがいます。」", rel:[], exp:"会話の流れに合う返事を選ぶ。"},
  {lv:10, stage:"dialog", q:"Mother: Are you hungry?\nSon: ( )", c:["Yes, I am.", "It's mine.", "On Sunday.", "Thank you."], a:0, kw:"確認", em:"🍽️", yaku:"「おなかすいた。」「うん、すいた。」", rel:[], exp:"会話の流れに合う返事を選ぶ。"},
  {lv:10, stage:"dialog", q:"Boy: Let's go to the zoo.\nGirl: ( )", c:["Sounds good!", "You're welcome.", "It's red.", "No, I'm not."], a:0, kw:"さそい", em:"🦁", yaku:"「動物園へ行こう。」「いいね！」", rel:[], exp:"会話の流れに合う返事を選ぶ。"},
  {lv:10, stage:"dialog", q:"Girl: Where is the station?\nMan: ( )", c:["It's near the park.", "It's Monday.", "Yes, it is.", "At six."], a:0, kw:"場所", em:"🚉", yaku:"「駅はどこ。」「公園の近くです。」", rel:[], exp:"会話の流れに合う返事を選ぶ。"},
  {lv:10, stage:"dialog", q:"Boy: How much is this pen?\nClerk: ( )", c:["It's two dollars.", "It's two o'clock.", "Yes, I do.", "At two."], a:0, kw:"値段", em:"💰", yaku:"「このペンいくら。」「2ドルです。」", rel:[], exp:"会話の流れに合う返事を選ぶ。"},
  {lv:10, stage:"order", q:"This is ___ pen.", c:["my", "I", "me", "mine"], a:0, kw:"", em:"🔤", yaku:"これはわたしのペンです。", rel:[], exp:"「わたしの」は my。"},
  {lv:10, stage:"order", q:"I ___ dogs.", c:["like", "likes", "am", "liking"], a:0, kw:"", em:"🔤", yaku:"わたしは犬が好きです。", rel:[], exp:"主語 I なので like。"},
  {lv:10, stage:"order", q:"He ___ soccer.", c:["plays", "play", "playing", "do"], a:0, kw:"", em:"🔤", yaku:"彼はサッカーをします。", rel:[], exp:"3人称単数は plays。"},
  {lv:10, stage:"order", q:"___ is this?", c:["What", "Who", "Where", "When"], a:0, kw:"", em:"🔤", yaku:"これは何ですか。", rel:[], exp:"「何」は What。"},
  {lv:10, stage:"order", q:"___ you a student?", c:["Are", "Is", "Do", "Am"], a:0, kw:"", em:"🔤", yaku:"あなたは学生ですか。", rel:[], exp:"You の be動詞疑問は Are。"},
  {lv:10, stage:"order", q:"I ___ twelve years old.", c:["am", "is", "are", "do"], a:0, kw:"", em:"🔤", yaku:"わたしは12歳です。", rel:[], exp:"I には am。"},
  {lv:10, stage:"order", q:"There ___ a book on the desk.", c:["is", "are", "am", "be"], a:0, kw:"", em:"🔤", yaku:"机の上に本があります。", rel:[], exp:"単数は There is。"},
  {lv:10, stage:"order", q:"I ___ English every day.", c:["study", "studies", "am", "is"], a:0, kw:"", em:"🔤", yaku:"わたしは毎日英語を勉強します。", rel:[], exp:"主語 I なので study。"},
  {lv:10, stage:"order", q:"She ___ play the piano.", c:["can", "cans", "is", "does"], a:0, kw:"", em:"🔤", yaku:"彼女はピアノをひけます。", rel:[], exp:"「できる」は can。"},
  {lv:10, stage:"order", q:"___ the door, please.", c:["Open", "Opens", "Opening", "To open"], a:0, kw:"", em:"🔤", yaku:"ドアを開けてください。", rel:[], exp:"命令文は原形。"},
  {lv:10, stage:"order", q:"I ___ running now.", c:["am", "is", "are", "do"], a:0, kw:"", em:"🔤", yaku:"わたしは今、走っています。", rel:[], exp:"I am+ing。"},
  {lv:10, stage:"order", q:"That is ___ house.", c:["my", "me", "I", "mine"], a:0, kw:"", em:"🔤", yaku:"あれはわたしの家です。", rel:[], exp:"「わたしの」は my。"},
  {lv:10, stage:"order", q:"We ___ friends.", c:["are", "am", "is", "be"], a:0, kw:"", em:"🔤", yaku:"わたしたちは友だちです。", rel:[], exp:"We には are。"},
  {lv:10, stage:"order", q:"___ you like cats?", c:["Do", "Are", "Is", "Does"], a:0, kw:"", em:"🔤", yaku:"あなたはねこが好きですか。", rel:[], exp:"一般動詞の疑問は Do。"},
  {lv:10, stage:"order", q:"He ___ not like natto.", c:["does", "do", "is", "are"], a:0, kw:"", em:"🔤", yaku:"彼は納豆が好きではありません。", rel:[], exp:"3人称単数の否定は does not。"},
  {lv:10, stage:"order", q:"I want ___ orange.", c:["an", "a", "the", "some"], a:0, kw:"", em:"🔤", yaku:"わたしはオレンジがほしい。", rel:[], exp:"母音の音の前は an。"},
  {lv:10, stage:"order", q:"I have three ___.", c:["books", "book", "a book", "bookes"], a:0, kw:"", em:"🔤", yaku:"わたしは本を3冊持っています。", rel:[], exp:"2つ以上は books。"},
  {lv:10, stage:"order", q:"My mother ___ a teacher.", c:["is", "are", "am", "do"], a:0, kw:"", em:"🔤", yaku:"わたしの母は先生です。", rel:[], exp:"3人称単数 mother は is。"},
  {lv:10, stage:"order", q:"___ play soccer.", c:["Let's", "Let", "Do", "We's"], a:0, kw:"", em:"🔤", yaku:"サッカーをしよう。", rel:[], exp:"「〜しよう」は Let's。"},
  {lv:10, stage:"order", q:"___ is your birthday?", c:["When", "Where", "Who", "What"], a:0, kw:"", em:"🔤", yaku:"あなたの誕生日はいつですか。", rel:[], exp:"「いつ」は When。"},
  {lv:10, stage:"order", q:"I get up ___ six.", c:["at", "in", "on", "to"], a:0, kw:"", em:"🔤", yaku:"わたしは6時に起きます。", rel:[], exp:"時こくの前は at。"},
  {lv:10, stage:"order", q:"They ___ in the park.", c:["are", "is", "am", "be"], a:0, kw:"", em:"🔤", yaku:"彼らは公園にいます。", rel:[], exp:"複数は are。"},
  {lv:10, stage:"order", q:"___ bag is this?", c:["Whose", "Who", "Which", "What"], a:0, kw:"", em:"🔤", yaku:"これはだれのかばんですか。", rel:[], exp:"「だれの」は Whose。"},
  {lv:10, stage:"order", q:"I ___ a new bike.", c:["want", "wants", "am", "is"], a:0, kw:"", em:"🔤", yaku:"わたしは新しい自転車がほしい。", rel:[], exp:"主語 I なので want。"},
  {lv:10, stage:"order", q:"She ___ well.", c:["swims", "swim", "swimming", "swam"], a:0, kw:"", em:"🔤", yaku:"彼女は上手に泳ぎます。", rel:[], exp:"3人称単数は swims。"},
  {lv:10, stage:"order", q:"The cat is ___ the box.", c:["in", "on", "under", "to"], a:0, kw:"", em:"🔤", yaku:"箱の中にねこがいます。", rel:[], exp:"「中に」は in。"},
  {lv:10, stage:"order", q:"___ old are you?", c:["How", "What", "Who", "When"], a:0, kw:"", em:"🔤", yaku:"あなたは何歳ですか。", rel:[], exp:"年齢は How old。"},
  {lv:10, stage:"order", q:"I like ___.", c:["music", "plays", "go", "is"], a:0, kw:"", em:"🔤", yaku:"わたしは音楽が好きです。", rel:[], exp:"「音楽」は music。"},
  {lv:10, stage:"order", q:"These ___ books.", c:["are", "is", "am", "do"], a:0, kw:"", em:"🔤", yaku:"これらは本です。", rel:[], exp:"These(複数)は are。"},
  {lv:10, stage:"order", q:"Please help ___.", c:["me", "I", "my", "mine"], a:0, kw:"", em:"🔤", yaku:"わたしを手伝ってください。", rel:[], exp:"「わたしを」は me。"},

  // ===== Lv11  英検4級 前編(語彙文法) =====
  {lv:11, stage:"grammar", q:"I went to the park ___ my friends.", c:["with", "of", "to", "at"], a:0, kw:"前置詞", em:"🌳", rel:[], exp:"「〜と一緒に」は with。"},
  {lv:11, stage:"grammar", q:"She ___ TV last night.", c:["watched", "watch", "watches", "watching"], a:0, kw:"過去形", em:"📺", rel:[], exp:"last night(過去)なので watched。"},
  {lv:11, stage:"grammar", q:"There ___ some books on the desk.", c:["are", "is", "am", "be"], a:0, kw:"There are", em:"📚", rel:[], exp:"books(複数)なので There are。"},
  {lv:11, stage:"vocab", q:"「昨日」は 英語で どれ？", c:["yesterday", "tomorrow", "today", "morning"], a:0, kw:"yesterday", em:"📆", rel:["today", "tomorrow"], exp:"昨日は yesterday。"},
  {lv:11, stage:"grammar", q:"He is taller ___ me.", c:["than", "as", "then", "of"], a:0, kw:"比較級", em:"📏", rel:[], exp:"比較級 -er のあとは than。"},
  {lv:11, stage:"vocab", q:"borrow の 意味は？", c:["借りる", "貸す", "買う", "売る"], a:0, kw:"borrow", em:"📖", rel:["lend"], exp:"borrow は 借りる。貸すは lend。"},
  {lv:11, stage:"grammar", q:"I was ___ TV when he came.", c:["watching", "watch", "watched", "watches"], a:0, kw:"過去進行形", em:"📺", rel:[], exp:"was + -ing で過去進行形。"},
  {lv:11, stage:"grammar", q:"Must I go now? — No, you ___.", c:["don't have to", "must not", "must", "aren't"], a:0, kw:"must", em:"⏰", rel:[], exp:"「〜しなくてよい」は don't have to。"},
  {lv:11, stage:"vocab", q:"invite の 意味は？", c:["招待する", "訪ねる", "注文する", "到着する"], a:0, kw:"invite", em:"✉️", rel:["visit"], exp:"invite は 招待する。"},
  {lv:11, stage:"grammar", q:"What ___ you do yesterday?", c:["did", "do", "does", "are"], a:0, kw:"過去疑問", em:"❓", rel:[], exp:"yesterday(過去)の疑問文は did。"},

  // ===== Lv12  英検4級 後編(会話読解) =====
  {lv:12, stage:"talk", q:"May I help you? — ___", c:["Yes, please.", "It's Monday.", "I'm fine.", "On the desk."], a:0, kw:"店員", em:"🛍️", rel:[], exp:"店での「お手伝いしましょうか」への返答。"},
  {lv:12, stage:"talk", q:"How was your weekend? — ___", c:["It was great.", "Yes, I do.", "It's mine.", "At three."], a:0, kw:"感想", em:"🎉", rel:[], exp:"How was 〜? には It was 〜. で答える。"},
  {lv:12, stage:"talk", q:"Could you open the window? — ___", c:["Sure.", "I'm ten.", "It's cold.", "No, thank you."], a:0, kw:"依頼", em:"🪟", rel:[], exp:"ていねいな依頼には Sure. などで応じる。"},
  {lv:12, stage:"talk", q:"How long does it take? — ___", c:["About ten minutes.", "It's mine.", "Yes, I can.", "In the box."], a:0, kw:"所要時間", em:"⏱️", rel:[], exp:"How long には About 〜 minutes.。"},
  {lv:12, stage:"talk", q:"Would you like some tea? — ___", c:["Yes, please.", "It's Sunday.", "I'm fine, thank you.", "At home."], a:0, kw:"すすめ", em:"🍵", rel:[], exp:"Would you like 〜? には Yes, please. 等。"},
  {lv:12, stage:"read", q:"Tom studies math after dinner every day. → いつ 数学を 勉強する？", c:["夕食後", "朝食前", "昼休み", "日曜だけ"], a:0, kw:"読解", em:"📐", rel:[], exp:"after dinner =「夕食後」。"},
  {lv:12, stage:"read", q:"The library is next to the station. → 図書館は どこ？", c:["駅のとなり", "公園の中", "学校の前", "川のそば"], a:0, kw:"読解", em:"📚", rel:[], exp:"next to 〜 =「〜のとなり」。"},
  {lv:12, stage:"talk", q:"Why were you late? — ___", c:["Because I missed the bus.", "Yes, I was.", "It's rainy.", "At school."], a:0, kw:"理由", em:"🚌", rel:[], exp:"Why には Because 〜 で理由を答える。"},
  {lv:12, stage:"talk", q:"What are you going to do tomorrow? — ___", c:["I'm going to visit my aunt.", "It was fun.", "Yes, I did.", "On Monday."], a:0, kw:"予定", em:"🗓️", rel:[], exp:"be going to の予定には同じ形で答える。"},
  {lv:12, stage:"read", q:"Ken has two brothers and one sister. → ケンの きょうだいは 何人？", c:["3人", "2人", "1人", "4人"], a:0, kw:"読解", em:"👨‍👩‍👦", rel:[], exp:"兄弟2人+姉妹1人=3人。"},
];
